### ISSUE TITLE
引用不到base中是value

### ISSUE THREAD

**Issue by ylmyg** [getActivity/AndroidProject#102]
框架版本【必填】：v13.2

问题描述【必填】：导入了Iibrary中的base和wiget两个moudle，在widght中也增加了implementation project(':library:base')，但是widght中是控件却引用不到base中的R.dimen.dp_12 很奇怪，请问我需要怎么改么？

复现步骤【必填】：引入自己项目

是否必现【必填】：是

出现问题的手机信息【必填】：Redmi

出现问题的安卓版本【必填】：android10

请回答
是部分机型还是所有机型都会出现【必答】：部分 目前只有一台手机

AndroidProject 最新的版本是否存在这个问题【必答】：是

是否已经查阅框架文档还未能解决的【必答】：是

issue 是否有人曾提过类似的问题【必答】：否

是否可以通过 AndroidProject 工程来复现该问题【必答】：否

使用原生的权限 API 是否会出现该问题【必答】：是

**Comment by ylmyg** [comment]
mLeftView.setPaddingRelative((int) getResources().getDimension(R.dimen.dp_15),
                (int) getResources().getDimension(R.dimen.dp_12),
                (int) getResources().getDimension(R.dimen.dp_15),
                (int) getResources().getDimension(R.dimen.dp_12));
        mRightView.setPaddingRelative((int) getResources().getDimension(R.dimen.dp_15),
                (int) getResources().getDimension(R.dimen.dp_12),
                (int) getResources().getDimension(R.dimen.dp_15),
                (int) getResources().getDimension(R.dimen.dp_12));
R.dimen.dp_12 这种都是红色的，已经在widght中增加引用base了。

**Comment by ylmyg** [comment]
sourceSets {
        main {
            // res 资源目录配置
            res.srcDirs(
                    'src/main/res',
                    'src/main/res-sw',
            )
        }
    }
引入你的module也已经加了

**Comment by getActivity** [comment]
小伙子，这个不属于框架的问题，而是属于你的个人问题，需要你这边自行处理一下。

**Comment by ylmyg** [comment]
我直接拷贝进去到appmoudle中，这样不是解决的办法
