### ISSUE TITLE
WrapRecyclerView使用时position不准确问题

### ISSUE THREAD

**Issue by 979881765** [getActivity/AndroidProject#104]
咨询问题，作者大大忙的情况下，就不用回复了

最新版本在使用WrapRecyclerView的时候，设置OnItemClick点击事件时，position不准确，通过debug发现在【BaseAdapter】61行代码处【如下代码】：holder.getAdapterPosition()获取的值使用是-1，所以导致 mPositionOffset默认就会偏移当前屏幕中显示的item数量

  @Override
    public final void onBindViewHolder(@NonNull VH holder, int position) {
        // 根据 ViewHolder 绑定的位置和传入的位置进行对比
        // 一般情况下这两个位置值是相等的，但是有一种特殊的情况
        // 在外层添加头部 View 的情况下，这两个位置值是不对等的
        mPositionOffset = position - holder.getAdapterPosition();
        holder.onBindView(position);
    }

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
