### ISSUE TITLE
CrashHandler类里在崩溃前用EasyHttp无法发起一个网络请求。

### ISSUE THREAD

**Issue by longcaiyinyuan** [getActivity/AndroidProject#106]
## 建议收集

* issue 是否有人曾提过类似的问题？没有提过。

* 你觉得框架有什么不足之处？【必答】我想让项目在发生重大的崩溃后将异常信息通过接口提交到后台，类似于做一个Bugly这样的功能。但bugly首先是一个第三方的，其次安卓技术中台首先就是一个框架我们完全自己可以实现这样的功能，我们自己做的异常处理可能更好更准确，处理崩溃会更迅速。就像我这次客户要求后台管理系统要有异常崩溃的上传信息记录，我总不能拿着bugly产品交付，所以想要在CrashHandler里在崩溃前发起一个网络请求将错误信息提交到后台来实现这个功能。

* 你觉得该怎么去完善会比较好？【非必答】在CrashHandler类里的uncaughtException方法获取到异常用EasyHttp网络框架提交，发现提交失败了，我怀疑是崩溃发生的太快，导致请求还未成功进程就结束了，于是我用Thread.sleep(3000);来延迟3s，让请求完成后在杀死进程，但我发现依然失败了。uncaughtException方法里有CrashActivity和RestartActivity的业务逻辑，发起一个网络请求的逻辑我觉得也是可以的，所以我怀疑是EasyHttp的问题，EasyHttp请求必须得有Lifecycle，这里用的是全局ApplicationLifecycle，我打断点发现EasyUtils.postDelayed(() 里的代码完全都没有执行，我猜测可能是崩溃发生后EasyHttp检测到LifecycleOwner已经销毁了，所以无法在执行下去了。我尝试用okhttp最原始的写法来发起请求：
   OkHttpClient okHttpClient = new OkHttpClient();
            RequestBody formBody = new FormBody.Builder()
                    .add("remote_result", remote_result)
                    .add("error_code", error_code)
                    .add("error_url", error_url)
                    .add("request_param", request_param)
                    .add("error_msg", error_msg)
                    .add("app_version", app_version)
                    .add("error_level", error_level)
                    .add("mac", MyUtils.getLocalMacAddress(mApplication))
                    .build();

            Request request = new Request.Builder()
                    .url(HttpConstants.IP + HttpConstants.CRASHUPLOAD)
                    .post(formBody)
                    .build();
 Call call = okHttpClient.newCall(request);
            call.enqueue(new Callback() {
                @Override
                public void onFailure(Call call, IOException e) {
                }

                @Override
                public void onResponse(Call call, Response response) throws IOException {
                }
            });
经过测试是可以实现这个需求的，但我这个请求没有生命周期的约束可能就存在内存泄露等问题了。EasyHttp可不可以发起一个在这种场景下的请求呢~就像飞机的黑匣子一样即使飞机坠毁了依然会记录数据发出信号，咱们这里即使程序崩溃了，还能最后在杀死进程前提交一波数据。

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* EasyHttp 的问题不要到 AndroidProject issue 中来提

* 这个问题属于 Bug，应该提 Bug 单，但是你提了建议单

请重新提一个 issue 并纠正以上问题

**Comment by longcaiyinyuan** [comment]
好的
