### ISSUE TITLE
good

### ISSUE THREAD

**Issue by swordbee** [getActivity/AndroidProject#108]
## 问题描述

* 框架版本【必填】：XXX

* 问题描述【必填】：XXX

* 复现步骤【必填】：XXX

* 是否必现【必填】：填是/否

* 出现问题的手机信息【必填】：请填写出现问题的品牌和机型

* 出现问题的安卓版本【必填】：请填写出现问题的 Android 版本

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分/全部（例如：某为，某 Android 版本会出现）

* AndroidProject 最新的版本是否存在这个问题【必答】：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的【必答】：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题【必答】：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题【必答】：是/否（排查一下是不是 AndroidProject 的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
