### ISSUE TITLE
webview加载某个地址 系统返回键返回 一直死循环 地址为 https://m.njzq.cn/hd22/khwyl/khwyl.jsp

### ISSUE THREAD

**Issue by 756230883** [getActivity/AndroidProject#110]
## 问题描述

* 框架版本【必填】：最新拉取的代码

* 问题描述【必填】：加载 https://m.njzq.cn/hd22/khwyl/khwyl.jsp 这个网址  滑动到最先面 点击 “立即开户” 进入到下一个页面 此时再点击系统返回键 返回不到上一个页面 而是在死循环当前页面

* 复现步骤【必填】：加载 https://m.njzq.cn/hd22/khwyl/khwyl.jsp 这个网址  滑动到最先面 点击 “立即开户” 进入到下一个页面 此时再点击系统返回键 返回不到上一个页面 而是在死循环当前页面

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：oppo reno3

* 出现问题的安卓版本【必填】：android12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部（例如：华为，鸿蒙2.0 版本会出现）

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，我尝试了一下，确实有这个问题，但是我看了网页回退的逻辑，目前来看是没有问题的，另外我看了一下网页的逻辑，它会经过一个中转的页面，然后在这个页面上会进行跳转，所以导致回退网页的时候又跳转回去了，你确定这个问题不是网页的问题？

**Comment by 756230883** [comment]
首先感谢轮子哥百忙之中的回答  这个页面在微信 或者手机上其他浏览器上都可以正常的回退 网页应该是没有问题吧

**Comment by getActivity** [comment]
微信的浏览器内核是 x5，你现在新建一个新的 Android Demo 工程，自己手写 WebView 的回退逻辑看看能不能复现这个问题？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
