### ISSUE TITLE
下载弹框   下载时  干掉了 进程  通知栏无法关闭 无法点击

### ISSUE THREAD

**Issue by 183883324** [getActivity/AndroidProject#111]
## 问题描述

* 框架版本【必填】：13.1

* 问题描述【必填】：进程杀了  通知栏没消失

* 复现步骤【必填】： 打开升级app弹框  杀掉进程

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米MIX 4

* 出现问题的安卓版本【必填】：12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：小米MIX 4  android12

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，根据你提供的复现步骤，结果无法复现到该问题，具体的复现步骤如下：

1. 打开升级对话框
2. 点击《立即更新》
3. 检查通知栏有没有显示下载进度
4. 最后从任务卡片划走应用

结果是应用被杀死了，通知栏的下载进度也消失了，我的手机是小米 12，Android 13，miui 14.0.4

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/220813385-18da3b28-78da-4b6a-b5e1-8a344d8a53c4.png)
