### ISSUE TITLE
打开网页有输入框，键盘弹出 会挡住输入框

### ISSUE THREAD

**Issue by songshuilin** [getActivity/AndroidProject#112]
## 问题描述     原工程换了个url ，然后测试 网页底部有输入框， 点击时 键盘挡住输入框了。

* 框架版本【必填】：最新

* 问题描述【必填】：必现

* 复现步骤【必填】：拉工程，只替换url地址   

* 是否必现【必填】：填是/否   是 

* 出现问题的手机信息【必填】：小米 Redmi K30 Pro

* 出现问题的安卓版本【必填】：Android 12

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
