### ISSUE TITLE
原工程只换了个url ，然后测试 该url网页底部有输入框， 点击时键盘挡住输入框了。

### ISSUE THREAD

**Issue by songshuilin** [getActivity/AndroidProject#113]
## 问题描述    键盘挡住输入框，未把输入框顶起

* 框架版本【必填】：最新

* 问题描述【必填】：键盘挡住输入框，未把输入框顶起

* 复现步骤【必填】：clone工程，替换url，然后run，进入我的页面，点击进入浏览器页面，输入底部带有输入框的url。键盘挡住输入框。 （测试url:  https://e.baidu.com/lp/lpapply6/?refer=109275870&bd_vid=11404625489872498888）

* 是否必现【必填】：   是

* 出现问题的手机信息【必填】：小米 Redmi K30 Pro

* 出现问题的安卓版本【必填】：Android 12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】： 没有看到

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
![45b7bc49524de2ccdfc363d6f202da95](https://user-images.githubusercontent.com/18466715/221461145-39def703-bb43-4a13-a672-357605921d60.jpg)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，关于这个问题的解决方案，你搭配这个框架应该就可以解决了：[https://github.com/liangjingkanji/soft-input-event](https://github.com/liangjingkanji/soft-input-event)

**Comment by songshuilin** [comment]
看了好像这个解决不了。  项目是webview 加载url，键盘是由网页弹起。看了这个方案，弹起键盘会把上面的输入框顶上去，但是顶上去会有个闪的过程，不咋丝滑  轮子哥有啥好的建议么  http://www.manongjc.com/detail/51-wbelifjtlbzuyld.html

**Comment by getActivity** [comment]
https://user-images.githubusercontent.com/28616817/221568298-ed77e6e3-5229-4e9c-8588-f418c3e79cb0.mp4

**Comment by getActivity** [comment]
小伙子，我用你提供的链接测试没有办法打开，我换成其他链接，底部有带输入框的那种，集成那个框架之后就可以解决了。

**Comment by songshuilin** [comment]
> 小伙子，我用你提供的链接测试没有办法打开，我换成其他链接，底部有带输入框的那种，集成那个框架之后就可以解决了。

感觉这个是前端做的？  输入框在底部， 监听到键盘弹起，整个H5页面顶起键盘高度。  轮子哥，你这个链接给下我这边试下

**Comment by getActivity** [comment]
https://chat.forchange.cn/

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
