### ISSUE TITLE
无法打印EasyHttp日志

### ISSUE THREAD

**Issue by 756230883** [getActivity/AndroidProject#114]
## 问题描述

* 框架版本【必填】：最新拉取代码

* 问题描述【必填】：无法打印EasyHttp日志（EasyHttp升级到最新版本11.6也是无法打印）单独运行EasyHttp 项目可以正常打印

* 复现步骤【必填】：登录页面 点击登录  没有日志

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：oppo reno3 。 华为 p30 pro

* 出现问题的安卓版本【必填】：android12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分（例如：oppo reno3 ，android12 版本会出现）

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：是  #70  看了也无法解决

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* EasyHttp 不要到 AndroidProject 的 issue 来提，请到 EasyHttp issue 去提

请重新提一个 issue 并纠正以上问题
