### ISSUE TITLE
使用日期选择的Dialog有个小建议

### ISSUE THREAD

**Issue by ChenXiaoYao407** [getActivity/AndroidProject#117]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】没有

* 你觉得框架有什么不足之处？【必答】就是在显示日期的时候，希望能有个方法，设置没有选中的颜色，我现在的UI是选中是一个#0AD39F，但是没有选中的是一个灰色的

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，经过甚至考虑，最终不采纳该建议，具体原因如下：
1. AndroidProject 的出现并不是为了一套代码实现任何需求，它只是帮你写了大量需要你自行实现的模板代码，但是有一些代码仍然要你根据业务细节来修改。
2. ndroidProject 的代码不像框架一样只读不能写，你如果有强定制化 UI 的需求，请自行修改源码实现，具体怎么修改需要你自行思考和编码了。
3. 还有我修改 AndroidProject 中的任何代码，都会考虑一个事情，是不是专门为了某个人而编码，是不是为了特殊需求而编码，如果是则会考虑有没有必要写，如果我写这段代码大概有 50% 的人都不会用到，那么大概率我是不会写这段代码，因为这段代码可能对你现在的需求来讲很有用，但是对于大部分人来讲其实是一坨冗余的代码。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
