### ISSUE TITLE
ActivityManager类里面的mActivitySet  新插入的activity存可能可能会错位

### ISSUE THREAD

**Issue by fuchengxin** [getActivity/AndroidProject#118]
## 问题描述 ActivityManager类里面的mActivitySet  新插入的activity存可能可能会错位

* 框架版本【必填】：13.1

* 问题描述【必填】：开多个activity，可能会存在顺序不对问题

* 复现步骤【必填】：多开几个activity

* 是否必现【必填】：偶现

* 出现问题的手机信息【必填】：小米4S

* 出现问题的安卓版本【必填】：android13

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：否

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：否

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
![image](https://user-images.githubusercontent.com/15795966/228170945-6cded0dd-4f41-4653-aac3-5a7c0ed4d501.png)
![image](https://user-images.githubusercontent.com/15795966/228172293-a38c0e76-3266-4219-85c2-077e60bd51d8.png)

如图，我的执行顺序是MainActivity，PhoneLoginActivity.PsdLoginActivity,WebActivity,但是走到webactivity时，它的下标在mActivitySet里面并不是最后一位，猜测是因为ArrayMap的key并不是按插入顺序排序的，能否用stact或者LinkedHashMap来代替这个集合呢？

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by fuchengxin** [comment]
纠正一下，是Stack 不是stact
![image](https://user-images.githubusercontent.com/15795966/228174023-633206c7-48ca-47f1-8eeb-ddf915823a0e.png)
多试几次，顺序仍然不同

**Comment by getActivity** [comment]
小伙子，我没有 Get 到你的点，你为什么要执着于要让 `mActivitySet` 集合是有序的？你是在这块有什么需求么？

**Comment by fuchengxin** [comment]
那就是我理解错误了，我以为你原意做的就是有序的，我这确实是有个需求，顺序开了ABCDEF6个页面，然后在F做操作关闭C以后的页面，就是C-F，所以需要有序去处理

**Comment by fuchengxin** [comment]
好的
