### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by alienufovn** [getActivity/AndroidProject#119]
My project have show a browser link but i want it which have to download anything or go to any applications store, how to add - codes for this issue

My first Android application link ( java code )

https://web.tresorit.com/l/lk0X6#2Nvhb_zjV6aJiWDfyQnPsg

**Comment by getActivity** [comment]
@alienufovn Hello, I only deal with bugs and suggestions of the framework at present, and will not deal with technical problems encountered by individuals for the time being, because open source does not make money and will not provide any technical services for individuals
