### ISSUE TITLE
Pad或手机分屏模式下 activity转场动画会闪黑屏

### ISSUE THREAD

**Issue by liverloop** [getActivity/AndroidProject#120]
## 问题描述

* 框架版本【必填】：最新

* 问题描述【必填】：Pad或手机分屏模式下 activity转场动画会闪黑屏

* 复现步骤【必填】：分屏模型下跳转Activity

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米平板及小米手机都必线

* 出现问题的安卓版本【必填】：Android 13

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是/否（排查一下是不是 AndroidProject 的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by liverloop** [comment]
是在横屏分屏模式下

**Comment by getActivity** [comment]
https://user-images.githubusercontent.com/28616817/234172506-112195ba-547f-47b8-82bc-be6e2a0c9ca3.mp4

**Comment by getActivity** [comment]
小伙子，根据你提供的复现步骤，我无法复现到该问题。

**Comment by liverloop** [comment]
https://user-images.githubusercontent.com/20295833/234317739-f651b0a5-6135-42a5-8c75-dd4c3470ba49.mp4

**Comment by liverloop** [comment]
左边是改的系统转场动画，右边是AndroidProject配置的转场动画，系统是miui14

**Comment by getActivity** [comment]
小伙子， 分屏在竖屏状态下使用 Activity 跳转动画不会出现闪黑屏的情况，但是在横屏状态下使用就会出现这种情况，这种问题很明显不就是厂商的问题？
