### ISSUE TITLE
 调用appadapter中removeItem后，后续item 的 position 不正确

### ISSUE THREAD

**Issue by jusyps** [getActivity/AndroidProject#121]
![1684461951774](https://github.com/getActivity/AndroidProject/assets/21016535/2aa70a32-676a-4272-b095-8e6525359466)

需要再调用一下 notifyItemRangeChanged 刷新

**Comment by dirkshowtime** [comment]
遇到类似的问题，这个adapter..不知道是我用的不对还是咋。看demo用的也没差啊。真的头疼。换成BRVAH了。
