### ISSUE TITLE
您好，在Android11机型上面，webview有时候会加载不出来。

### ISSUE THREAD

**Issue by WangkeqiangS** [getActivity/AndroidProject#123]
## 问题描述

* 框架版本【必填】：最新版

* 问题描述【必填】：Android11上面，webview一直加载，没有走onPageStarted回调。

* 复现步骤【必填】：在框架中打开加载网页界面

* 是否必现【必填】：概率性问题，多次重新运行项目就会出现

* 出现问题的手机信息【必填】：pda手机

* 出现问题的安卓版本【必填】：Android11

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分手机，没有多余的Android11设备

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否
* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是
* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="530" alt="image" src="https://github.com/getActivity/AndroidProject/assets/28616817/5b4dab41-442c-4b60-ae96-5546a59b548c">

小伙子，我自己在 Android 11 试过了是没有问题，你是加载什么网页有这个问题？还有这个问题你试试看其他机型会不会出现？

**Comment by getActivity** [comment]
超过三个星期没有响应，自动关闭此 issue。
