### ISSUE TITLE
把个人中心activity的布局，写在fragment里的时候点击头像条目下方的条目，头像条目有选中的效果

### ISSUE THREAD

**Issue by lyphia** [getActivity/AndroidProject#124]
## 问题描述

* 框架版本【必填】：最新版

* 问题描述【必填】：把个人中心fragment的布局，写在activity里的时候点击头像条目下方的条目，头像条目有选中的效果

* 复现步骤【必填】：git clone项目=》点击我的=》个人中心页面，把personal_data_activity布局放在首页新建的fragment里边，重启项目，点击到刚才修改的页面

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：iQOO 9 pro

* 出现问题的安卓版本【必填】：Android13

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分机型，没有多余机型（除了iQOO9pro）
* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是
## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

https://github.com/getActivity/AndroidProject/assets/58797187/e10fe720-d7f9-4272-9eac-7dbdfbf4ff8b

* 提供截图或视频（根据需要提供，此项不强制）
* 

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by 330132662** [comment]
我也遇到过  ，在你想有点击效果的地方加上 clickable=true 试试

**Comment by lyphia** [comment]
> 我也遇到过 ，在你想有点击效果的地方加上 clickable=true 试试

感谢大佬，可以了，我加了个背景设置，去掉就好了

**Comment by 330132662** [comment]
本邮箱不作为工作生活用 请联系 ***@***.***
