### ISSUE TITLE
androidx.appcompat:appcompat升级

### ISSUE THREAD

**Issue by yibella** [getActivity/AndroidProject#125]
* issue 是否有人曾提过类似的问题？【必答】（没有）

* 你觉得框架有什么不足之处？【必答】（大佬，可以升级以下androidx.appcompat:appcompat吗，项目中是1.3.1，现在最新版本是1.5.0了。因为1.5.0版本中自带LifecycleOwner了且有一个fina的getLifecycle方法冲突了）

**Comment by getActivity** [comment]
小伙子，为什么要升级 AppCompat 依赖库的版本？

**Comment by yibella** [comment]
大佬说的我竟无言以对了

**Comment by getActivity** [comment]
@yibella 小伙子，如果想要 AndroidX 最新版，那么你可以自己升级，没有必要一定要依赖我才行，只不过你如果是自己升级的话，中间遇到的各种问题，需要你自行解决，还用一种方法，要等 AndroidProject 升级，不过这个选择由我决策，我要根据具体的情况而定，考虑的方面会很多，你可能等不及，因为我是一个求稳的人，而不是追求新技术的人。
