### ISSUE TITLE
关于目前App比较常态化得问题

### ISSUE THREAD

**Issue by 752375734** [getActivity/AndroidProject#126]
## 建议

* 在申请打开存储权限时，未同步告知用户其目的？【非必答】

* 征得用户同意隐私政策前，App私自收集个人信息？【必答】（在同意隐私政策前不要有任何得收集动作）

* Webview File同源策略绕过漏洞？【非必答】

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
