### ISSUE TITLE
布局中有androidx.core.widget.NestedScrollView组件会阻断BaseActivity中点击空白收起键盘的逻辑

### ISSUE THREAD

**Issue by chen3441251** [getActivity/AndroidProject#127]
## 问题描述

* 框架版本【必填】：最新

* 问题描述【必填】：布局中有androidx.core.widget.NestedScrollView组件会阻断BaseActivity中点击空白收起键盘的逻辑

* 复现步骤【必填】：我的-点击进去登录页面-忘记密码-布局嵌套一层NestedScrollView，点击空白区域就无法收起键盘（所有布局如果有NestedScrollView都会影响到BaseActivity点击空白收起键盘）

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为 mate30 pro

* 出现问题的安卓版本【必填】：Android12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈 无报错信息，应该是NestedScrollView拦截了点击事件

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案：目前是在baseActivity中通过getContentView获取当前页面布局view，然后遍历当前布局，如果有NestedScrollView则取NestedScrollView的子view作为空白点击的view；
* 目前通过以下方式来解决是最简单的，如果从NestedScrollView着手可能需要自定义NestedScrollView。轮子哥看看有无更好的解决方案，核心代码如下：

```
package com.hjq.base.BaseActivity
 /**
     * 初始化软键盘
     */
    protected void initSoftKeyboard() {
        // 点击外部隐藏软键盘，提升用户体验
      // 1.遍历当前布局找出是否存在NestedScrollView 
        NestedScrollView nestedScrollView = obtainNestedScrollView(getContentView());
        //2.默认是取当前布局的rootview
        View activeView = getContentView();
        //3.如果存在NestedScrollView ，则取其子view
        if (nestedScrollView != null) {
            activeView = nestedScrollView.getChildAt(0);
        }
     //4.设置点击事件
        if (activeView != null) {
            activeView.setOnClickListener(v -> hideKeyboard(getCurrentFocus()));
        }
    }

 /**
     * 递归获取 ViewGroup 中的 NestedScrollView 对象
     */
    NestedScrollView obtainNestedScrollView(ViewGroup group) {
        for (int i = 0; i < group.getChildCount(); i++) {
            View view = group.getChildAt(i);
            if ((view instanceof NestedScrollView)) {
                return (NestedScrollView) view;
            } else if (view instanceof ViewGroup) {
                NestedScrollView nestedScrollView = obtainNestedScrollView((ViewGroup) view);
                if (nestedScrollView != null) {
                    return nestedScrollView;
                }
            }
        }
        return null;
    }
```

**Comment by getActivity** [comment]
小伙子，对于这个问题，我没有更好的解决方案，不过这个问题我觉得可以根据场景来进行适配，而不是直接写到 BaseActivity 中，这样写可能不太合理。

**Comment by chen3441251** [comment]
> 小伙子，对于这个问题，我没有更好的解决方案，不过这个问题我觉得可以根据场景来进行适配，而不是直接写到 BaseActivity 中，这样写可能不是很合理。

好的。那根据场景来适配好了，谢谢轮子哥
