### ISSUE TITLE
BaseActivity:startActivityForResult疑惑

### ISSUE THREAD

**Issue by tao566** [getActivity/AndroidProject#128]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）：
应该翻遍了所有issue。没有找到答案

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）：
     在这个方法中，您使用了随机值赋予给requestCode，用键值对的形式存储对应回调接口。我认为您的优化使得requestCode的存在已经失去了意义：原因如下：requestCodes的最初的意义我想大概是以下原因：存在多个地方进行startActivityForResult的不同活动跳转，回来时都聚集在onResult中，为了“辨别”是从那个活动回来的，采用了requestCode来辨别。但您的优化方法使得每一个回来的回调都只是通过onResult这个”暂留点“转到自己对应的那个callback，这已经实现了“辨别”；再考虑到活动同一时间只能调用代码处某一个startActivityForResult，这使得回来的也只有一个callback，因此我认为也不需要通过SparseArray.get(requestCode)来获取回调接口，甚至说SparseArray都不需要。

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）：
   （我只有不到一年的Android学习经验，因此以上理解可能存在很大问题，希望作者您可以帮我分析一下。如果有问题以下的改写就不浪费您的时间了）
   1：requestCode没有必要随机化赋值，直接super.startActivityForResult(intent,0);   
   2：SpareArray不需要，只需要创建一个OnActivityCallback mCallback成员变量，之后在重写startActivityForResult时，mCallback = callback；在重写onActivityResult时， mCallback.onActivityResult(resultCode, data);

**Comment by getActivity** [comment]
> 活动同一时间只能调用代码处某一个 `startActivityForResult`

小伙子，你这个结论是怎么得来的？

**Comment by tao566** [comment]
看来有同时跳转多个活动的需求场景，是我经验还不够，懂了，谢谢您了
