### ISSUE TITLE
日期dialog 设置当前日期为2018-12-31, 但页面上显示的是2018-12-30

### ISSUE THREAD

**Issue by qianxun627** [getActivity/AndroidProject#129]
## 问题描述

* 框架版本【必填】：当前最新版本

* 问题描述【必填】：我本地拉下项目, 运行完后, 发现日期dialog 设置当前日期为2018-12-31, 但页面上显示的是2018-12-30

* 复现步骤【必填】：DialogActivity ==> 日期对话框 ==> 放开注释的 .setDate("2018-12-31") ==> 运行后发现选中的日期是2018-12-30

* 是否必现【必填】：是

**Comment by getActivity** [comment]
<img width="1473" alt="image" src="https://github.com/getActivity/AndroidProject/assets/28616817/5aa142d6-d9e8-42c0-bb89-de90b9edf77a">

**Comment by getActivity** [comment]
小伙子，你把代码修改成这样看看问题还有没有出现？

**Comment by getActivity** [comment]
超过三个星期没有响应，自动关闭此 issue。
