### ISSUE TITLE
大佬，一丢丢小小的建议

### ISSUE THREAD

**Issue by maoai-xianyu** [getActivity/AndroidProject#13]
大佬，还可以添加一些功能，eg Activity管理，fragment管理

**Comment by getActivity** [comment]
因为这个功能不是必须的，所以现在暂时不考虑

**Comment by maoai-xianyu** [comment]
我们一般不是会有退出登录等等一些操作，让用户重回登录页面等，不就需要清理应用的中未关掉的页面么..还有一些fragment。 不过也是，这个因项目而异。Thanks

**Comment by getActivity** [comment]
这个问题我已经考虑到了，项目中已经有了Activity管理的类了，但是Fragment没有
