### ISSUE TITLE
项目缺少 com.hjq.demo.http.glide.GlideApp 文件

### ISSUE THREAD

**Issue by wyh497823256** [getActivity/AndroidProject#130]
## 问题描述

* 框架版本【必填】：当前最新

* 问题描述【必填】：项目缺少 com.hjq.demo.http.glide.GlideApp 文件

* 复现步骤【必填】：XXX

* 是否必现【必填】：是

* 提供截图或视频（根据需要提供，此项不强制）

![image](https://github.com/getActivity/AndroidProject/assets/8830870/7657330e-13c8-4c0c-882d-c36df1aeaeef)

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
