### ISSUE TITLE
Q群满了老哥 进不去啊

### ISSUE THREAD

**Issue by yzjjdcf** [getActivity/AndroidProject#131]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
一群人满了，二群号：10047167
