### ISSUE TITLE
打开 AndroidProject APP，LeakCanary 检测启动页出现内存泄露

### ISSUE THREAD

**Issue by chen-fuhai** [getActivity/AndroidProject#133]
## 问题描述

* 框架版本【必填】：v13.1

* 问题描述【必填】：打开 AndroidProject APP，LeakCanary 检测启动页出现内存泄露

* 复现步骤【必填】：打开 AndroidProject APP

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：荣耀 Magic5

* 出现问题的安卓版本【必填】：Android 13

## 请回答

* 是部分机型还是所有机型都会出现【必答】：荣耀， Android 13

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

https://github.com/getActivity/AndroidProject/assets/64265495/7d742a2d-df43-40b1-9e35-3d28ffabce12

![QQ图片20231106210838](https://github.com/getActivity/AndroidProject/assets/64265495/51eba2df-e1e9-43b3-bc16-fe616f83911b)
![QQ图片20231106210848](https://github.com/getActivity/AndroidProject/assets/64265495/eb8d6919-4e42-4c5e-9c73-ebae015a15d7)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，你怎么认定这个内存泄漏是 AndroidProject 而不是 MagicOs 导致的？

**Comment by chen-fuhai** [comment]
我目前只有这台机型使用，请问一下，如何排查是那种原因导致的吗？

**Comment by getActivity** [comment]
小伙子，从内存泄漏的堆栈来看，这个就是 MagicOs 系统代码引发的内存泄漏，和框架没有什么关系。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。

**Comment by chen-fuhai** [comment]
好的，谢谢
