### ISSUE TITLE
gradle升到7+以后aop切面不适配了

### ISSUE THREAD

**Issue by fuchengxin** [getActivity/AndroidProject#134]
## 建议收集  gradle升到7+以后aop切面不适配了，一键注解请求权限感觉确实很好用，请问轮子哥有准备适配或者有新的适配方式吗

* issue 是否有人曾提过类似的问题？【必答】否

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 乱填 issue 问题

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写

**Comment by lixiang0418** [comment]
https://github.com/wurensen/gradle_plugin_android_aspectjx/tree/master
参照上面链接可以解决你的问题，轮子哥在https://github.com/getActivity/AndroidProject/issues/103里有提到
