### ISSUE TITLE
关于使用TabAdapter配合ViewPager时，导航栏超出屏幕范围后滑动viewpager时导航栏item不显示

### ISSUE THREAD

**Issue by shinobu59** [getActivity/AndroidProject#135]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】（翻遍了issue，应该没有）

* 你觉得框架有什么不足之处？【必答】（当使用TabAdapter配合ViewPager时，tabadapter设置不固定宽度，item过多超出屏幕范围后，滑动viewpager时，如果目标viewpage联动的tab item不可见时，不会自动滑动到屏幕可见范围内）

* 你觉得该怎么去完善会比较好？【非必答】
* 我稍微改动了一下TabAdapter，不知道这样改是否合理，是否有更好的方法，代码如下：
```
public void setSelectedPosition(int position) {

        if (mSelectedPosition == position) {
            return;
        }

        notifyItemChanged(mSelectedPosition);

        mSelectedPosition = position;

        notifyItemChanged(position);

       //以下代码是我新增的

        if (!mFixed) {
            int firstVisibleItemPosition = ((LinearLayoutManager)getRecyclerView().getLayoutManager()).findFirstVisibleItemPosition();

            int lastVisibleItemPosition = ((LinearLayoutManager)getRecyclerView().getLayoutManager()).findLastVisibleItemPosition();

            if (position > lastVisibleItemPosition || position < firstVisibleItemPosition) {

                ((LinearLayoutManager)getRecyclerView().getLayoutManager()).scrollToPositionWithOffset(position, 0);

            }
        }
    }
```

**Comment by shinobu59** [comment]
你的代码更严谨一些，我把我的改了，那我就关闭issue了

**Comment by shinobu59** [comment]
我又研究了一下，我觉得将findFirstVisibleItemPosition替换成findFirstCompletelyVisibleItemPosition，findLastVisibleItemPosition替换成findLastCompletelyVisibleItemPosition效果更好一点，完整代码如下：
```
LinearLayoutManager linearLayoutManager = (LinearLayoutManager) layoutManager;
        // 获取第一个和最后一个可见的条目位置
        int firstVisibleItemPosition = linearLayoutManager.findFirstCompletelyVisibleItemPosition();
        int lastVisibleItemPosition = linearLayoutManager.findLastCompletelyVisibleItemPosition();

        // 如果是在可视区域范围内，则不往下执行
        if (position >= firstVisibleItemPosition && position <= lastVisibleItemPosition) {
            return;
        }
        // 处理在 Tab 过多的情况下，选中某个 Tab 选项中没有滚动的问题
        linearLayoutManager.scrollToPosition(position);
```

**Comment by shinobu59** [comment]
> 小伙子，经过核实，确实存在这个问题，非常感谢小伙子提出问题，目前我已经处理了该问题，另外提供我写的代码供你参考
> 
> ```java
> public void setSelectedPosition(int position) {
>     if (mSelectedPosition == position) {
>         return;
>     }
>     notifyItemChanged(mSelectedPosition);
>     mSelectedPosition = position;
>     notifyItemChanged(position);
> 
>     // 如果当前是宽度对等的模式，则不继续往下执行
>     if (mFixed) {
>         return;
>     }
> 
>     RecyclerView recyclerView = getRecyclerView();
>     if (recyclerView == null) {
>         return;
>     }
> 
>     LayoutManager layoutManager = recyclerView.getLayoutManager();
>     if (layoutManager == null) {
>         return;
>     }
> 
>     // 注意：GridLayoutManager 是 LinearLayoutManager 的子类
>     if (!(layoutManager instanceof LinearLayoutManager)) {
>         return;
>     }
> 
>     LinearLayoutManager linearLayoutManager = (LinearLayoutManager) layoutManager;
>     // 获取第一个和最后一个可见的条目位置
>     int firstVisibleItemPosition = linearLayoutManager.findFirstVisibleItemPosition();
>     int lastVisibleItemPosition = linearLayoutManager.findLastVisibleItemPosition();
> 
>     // 如果是在可视区域范围内，则不往下执行
>     if (position > firstVisibleItemPosition && position < lastVisibleItemPosition) {
>         return;
>     }
>     // 处理在 Tab 过多的情况下，选中某个 Tab 选项中没有滚动的问题
>     linearLayoutManager.scrollToPositionWithOffset(position, 0);
> }
> ```

我又研究了一下，我觉得将findFirstVisibleItemPosition替换成findFirstCompletelyVisibleItemPosition，findLastVisibleItemPosition替换成findLastCompletelyVisibleItemPosition，scrollToPositionWithOffset替换成scrollToPosition效果更好一点，完整代码如下：
```
        LinearLayoutManager linearLayoutManager = (LinearLayoutManager) layoutManager;
        // 获取第一个和最后一个可见的条目位置
        int firstVisibleItemPosition = linearLayoutManager.findFirstCompletelyVisibleItemPosition();
        int lastVisibleItemPosition = linearLayoutManager.findLastCompletelyVisibleItemPosition();

        // 如果是在可视区域范围内，则不往下执行
        if (position >= firstVisibleItemPosition && position <= lastVisibleItemPosition) {
            return;
        }
        // 处理在 Tab 过多的情况下，选中某个 Tab 选项中没有滚动的问题
        linearLayoutManager.scrollToPosition(position);
```

**Comment by getActivity** [comment]
* 收到，感谢小伙子的建议，目前优化后的代码如下：

```java
public void setSelectedPosition(int position) {
    if (mSelectedPosition == position) {
        return;
    }
    int oldPosition = mSelectedPosition;
    mSelectedPosition = position;
    notifyItemChanged(oldPosition);
    notifyItemChanged(mSelectedPosition);

    // 如果当前 Tab 宽度是对等的模式，则不继续往下执行
    if (mFixed) {
        return;
    }

    RecyclerView recyclerView = getRecyclerView();
    if (recyclerView == null) {
        return;
    }

    LayoutManager layoutManager = recyclerView.getLayoutManager();
    if (layoutManager == null) {
        return;
    }

    // 注意：GridLayoutManager 是 LinearLayoutManager 的子类
    if (!(layoutManager instanceof LinearLayoutManager)) {
        return;
    }

    LinearLayoutManager linearLayoutManager = (LinearLayoutManager) layoutManager;
    // 获取第一个和最后一个完全可见的条目位置
    int firstCompletelyVisibleItemPosition = linearLayoutManager.findFirstCompletelyVisibleItemPosition();
    int lastCompletelyVisibleItemPosition = linearLayoutManager.findLastCompletelyVisibleItemPosition();

    // 如果是在可视区域范围内，则不往下执行
    if (position >= firstCompletelyVisibleItemPosition && position <= lastCompletelyVisibleItemPosition) {
        return;
    }
    // 处理在 Tab 过多的情况下，选中某个 Tab 选项中没有自动滚动的问题
    linearLayoutManager.scrollToPosition(position);
}
```
