### ISSUE TITLE
AppActivity实现OnHttpListener意义是什么？

### ISSUE THREAD

**Issue by bibubi** [getActivity/AndroidProject#136]
## 问题描述

* 框架版本【必填】：最新版 + EasyHttp:10.2/12.6

* 问题描述【必填】：
Demo中使用 EasyHttp:10.2，在  EasyHttp.post(this).request(this);时候，Activity的onSucceed进行Object转换HttpData
![image](https://github.com/getActivity/AndroidProject/assets/18078927/e9f7de08-2803-4c88-b592-98e2af3642d1)
Demo中使用 EasyHttp:12.6，在  EasyHttp.post(this).request(this);时候，Activity的onHttpSuccess进行Object转换HttpData
![image](https://github.com/getActivity/AndroidProject/assets/18078927/b506200d-753f-43cb-86fd-89337f97e87e)

* 复现步骤【必填】：Activity实现OnHttpListener / 继承AppActivity

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：荣耀 20、红米K20

* 出现问题的安卓版本【必填】：Android 10、11

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个属于 [EasyHttp](https://github.com/getActivity/EasyHttp) 框架的问题，请到对应框架的 [issue](https://github.com/getActivity/EasyHttp/issues) 提该问题

请重新提一个 issue 并纠正以上问题
