### ISSUE TITLE
查看大图模块中onItemClick position 返回值问题

### ISSUE THREAD

**Issue by maerchicao** [getActivity/AndroidProject#137]
## 问题描述

* 框架版本【必填】：[v13.1]

* 问题描述【必填】：查看大图模块，图片点击的时候，position提示位置和时间不对应

* 复现步骤【必填】：点击关闭图片，position提示和实际不匹配，比如当前点击第一张图片，提示1，点击第二张图片还提示1。

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：三星S9

* 出现问题的安卓版本【必填】：所有版本都会

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：是

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
```
ImagePreviewActivity 类中 
  @Override
    public void onItemClick(RecyclerView recyclerView, View itemView, int position) {
        if (isFinishing() || isDestroyed()) {
            return;
        }
        toast(mAdapter.getItem(position)); // 多个图片点击的时候，返回的position 位置都为同一个值，和实际不对应
        // 单击图片退出当前的 Activity
        finish();
    }
```

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
[BaseAdapter.java.zip](https://github.com/getActivity/AndroidProject/files/14024572/BaseAdapter.java.zip)

**Comment by getActivity** [comment]
小伙子，这个是由于 BaseAdapter 在回调 onItemClick、onChildClick、onItemLongClick、onChildLongClick 方法时传入的位置有误导致的，请下载上面两个文件，参考相关的代码进行修改。

**Comment by maerchicao** [comment]
感谢大佬
