### ISSUE TITLE
建议增加一个下载网络图片到相册的功能

### ISSUE THREAD

**Issue by gaoxuge521** [getActivity/AndroidProject#138]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）
* 没搜到

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）
* 建议增加一个下载网络图片到相册的功能

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）
* 建议增加一个下载网络图片到相册的功能，国内各个手机搞得人焦头烂额，希望轮子哥出一个适配各手机大厂的方法

**Comment by getActivity** [comment]
小伙子，经过认真思考和斟酌，暂不采纳这个建议，这是因为这个功能不是 App 必备或者常用的功能。
