### ISSUE TITLE
Demo项目的BuildConfig.HOST_URL在不同环境中始终不变

### ISSUE THREAD

**Issue by moneeWong** [getActivity/AndroidProject#139]
## 问题描述

* 框架版本【必填】：V13.1

* 问题描述【必填】：原Demo项目（升级gradle-7.2-bin）通过Build Variant切换环境BuildConfig.HOST_URL值始终不变

* 复现步骤【必填】：Build Variant切换debug，preview，release 环境，每次都 Clean Project和Rebuild Project

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：Android Studio 模拟器，雷电模拟器（v9.0.66），华为Mate 40 Pro 5G（鸿蒙4.0）

* 出现问题的安卓版本【必填】：全部

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

![1709125250888](https://github.com/getActivity/AndroidProject/assets/17845920/654d4baa-8476-4f7c-abbe-94953582bb3c)

这个信息是你自己在项目里打印的，我发现不管是切换什么环境，始终打印的是这个，我根据你的信息，找到了 config.gradle
文件，猜测是这两个地方没达到预期功能，希望修复后能告知原因感谢
1、def taskName = project.gradle.startParameter.taskNames[0]
2、serverType = project.properties["ServerType"]

Android Studio 版本：Android Studio Hedgehog | 2023.1.1 Patch 2
Gradle 版本 ：7.2
Plugin 版本：4.1.2

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/getActivity/AndroidProject/assets/28616817/d532e9c3-088e-4572-8e3c-8be15e481015">

<img width="1680" alt="image" src="https://github.com/getActivity/AndroidProject/assets/28616817/ea5d9702-4be9-4446-8c6c-8678f9ef68e0">

**Comment by getActivity** [comment]
小伙子，我用 AndroidProject 进行测试，没有发现出现这个问题，我猜测可能是你的 Gradle 版本和我的不一样，我用的是 `gradle-7.2-all`，你用的是 `gradle-7.1-bin`，请参考这个 [issue/103](https://github.com/getActivity/AndroidProject/issues/103) 对 Gradle 版本进行升级。

**Comment by moneeWong** [comment]
> 小伙子，我用 AndroidProject 进行测试，没有发现出现这个问题，我猜测可能是你的 Gradle 版本和我的不一样，我用的是 `gradle-7.2-all`，你用的是 `gradle-7.1-bin`，请参考这个 [issue/103](https://github.com/getActivity/AndroidProject/issues/103) 对 Gradle 版本进行升级，然后看看问题还会不会出现。

经切换多个gradle版本测试，确实是“-bin”版本的gradle造成的错误，“-all”版本均无问题，感谢
