### ISSUE TITLE
当焦点发现页面的验证码EditText上时，底部导航栏会随软键盘一同弹起

### ISSUE THREAD

**Issue by weibindev** [getActivity/AndroidProject#14]

**Comment by getActivity** [comment]
这个Bug是由于线性布局的权重导致，我之前已经修复过这个，将ViewPager的高度定死，但是会导致手机底部导航栏将BottomNavigationView遮盖住一部分，考虑到主页界面中的出现EditText的情况极少，所以不考虑进行修复，谢谢
