### ISSUE TITLE
缺少GlideApp文件

### ISSUE THREAD

**Issue by QQ690898091** [getActivity/AndroidProject#140]
## 问题描述

* 框架版本【必填】：13.1

* 问题描述【必填】：缺少GlideApp文件

* 复现步骤【必填】：AppApplication中导入的文件import com.hjq.demo.http.glide.GlideApp缺失;

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为

* 出现问题的安卓版本【必填】：10.0

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部
* AndroidProject 最新的版本是否存在这个问题【必答】：是
* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

![1709211531009](https://github.com/getActivity/AndroidProject/assets/131941905/e68b4164-d981-48af-9f30-af8b29b9e4f4)

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 乱填 issue 问题

请重新提一个 issue 并纠正以上问题
