### ISSUE TITLE
BrowserActivity内存泄漏，网页界面空白

### ISSUE THREAD

**Issue by FanXH123** [getActivity/AndroidProject#143]
## 问题描述

* 框架版本【必填】：v13.1

* 问题描述【必填】：在点击“我的”→“点我进入设置界面”→“隐私协议”，重复点击隐私协议再退出再点击进入隐私协议界面后，网页会显示空白，只能下拉刷新才能加载出来，且会出现内存泄漏的情况，如下图
![微信图片_20240606101933](https://github.com/getActivity/AndroidProject/assets/16459353/ea7a77a7-1970-40c1-b699-9fd06a0b67e8)

* 复现步骤【必填】：重复点击隐私协议再退出再点击进入隐私协议界面

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：iqoo z8

* 出现问题的安卓版本【必填】：14

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，从堆栈分析，这个问题是你的手机 chrome 内核版本代码出现了内存泄漏，和 AndroidProject 没有关系，你可以换其他手机测试一下，关于这个问题的解决方案，建议升级 chrome 内核或者反馈给 chrome 官方处理。
