### ISSUE TITLE
现在的项目不存在问题，使用中台重构项目，两个lib依赖会冲突，为此特意新建项目写了个Demo，同时引用也不存在问题，使用中台，必现

### ISSUE THREAD

**Issue by ILoveLin** [getActivity/AndroidProject#144]
## 问题描述

* 框架版本【必填】：AndroidProject-13.1

* 问题描述【必填】：
现在线上的App 也同时引入了这两个库，是OK的，最近想重构项目就使用AndroidProject-13.1中台重构，就出现了不兼容问题，为此，我特意下载AndroidProject-13.1 源代码，直接引入两个库，还是一样必现，我特意写了个Demo，也同时引入两个库，也是OK的，所以再次特意请教下轮子哥。已下是具体描述。

引入vlclib（[vlc播放器库]https://github.com/ILoveLin/VlcRecordPlayer中的libvlc ）和 implementation'com.arthenica:ffmpeg-kit-full:5.1'  两者会产生一个冲突，ffmpeg-kit库中给了解决方案（线上项目和Demo也这么写的，中台项目添加了但是没有效果），在.build.gradle，新增
					              android {
								              packagingOptions {
									              pickFirst 'lib/x86/libc++_shared.so'
									              pickFirst 'lib/x86_64/libc++_shared.so'
									              pickFirst 'lib/armeabi-v7a/libc++_shared.so'
									              pickFirst 'lib/arm64-v8a/libc++_shared.so'
								              }
							              }

但是当我点击中台App的VLC播放界面会闪退。然而，我自己新建一个Demo，同时引入两个库，添加packagingOptions ，* * 在Demo中点击VLC播放界面就没问题。

* 复现步骤【必填】：在AndroidProject-13.1中台项目中，
第一步：下载(https://github.com/ILoveLin/VlcRecordPlayer)项目，然后引入项目中的libvlc，Module，到中台
                                               
第二步：在中台项目中 引入implementation 'com.arthenica:ffmpeg-kit-full:5.1'  在. build.gradle下新增
                                                                  android {
								                packagingOptions {
									                pickFirst 'lib/x86/libc++_shared.so'
									                pickFirst 'lib/x86_64/libc++_shared.so'
									                pickFirst 'lib/armeabi-v7a/libc++_shared.so'
									                pickFirst 'lib/arm64-v8a/libc++_shared.so'
								                }
							                }
                
第三步：在中台项目中新建一个VLC播放界面，初始化的时候就startLive，直接闪退

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：都闪退

* 出现问题的安卓版本【必填】：全部

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）
* 备注说明：
   我现如今的项目使用到了vlc录像和ffmpeg-kit-full:5.1，按照ffmpeg-kit-给的解决方案，我添加了packagingOptions 就解决了问题，现在项目也正常运转。
这个是我写的Demo：https://github.com/ILoveLin/VlcRecordPlayer 这个Demo  也集成了VLClib和ffmpeg-kit-full:5.1，也是OK的，最近我在用AndroidProject-13.1中台，重构自己的项目，但是当我进行的vlc播放功能的时候，就出现了问题，我试了好多种方法都没成功，不是很懂gradle 语言，但是我感觉应该是. build.gradle，配置问题，所以特来请教下

**Comment by getActivity** [comment]
小伙子，根据你提供的描述，我无法确定这个问题是不是 AndroidProject 的问题，请你确认好这个问题是 AndroidProject 再找我处理。

**Comment by ILoveLin** [comment]
好的
