### ISSUE TITLE
插拔USB键盘或者扫描枪的时候会重启app，会有内存泄露

### ISSUE THREAD

**Issue by qiefeimao** [getActivity/AndroidProject#145]
## 问题描述

* 框架版本【必填】：v13.1

* 问题描述【必填】：插拔USB键盘或者扫描枪的时候会重启app，会有内存泄露

* 复现步骤【必填】：插拔USB键盘或者扫描枪

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：Redmo Pad SE

* 出现问题的安卓版本【必填】：14

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

![微信图片_20240909085051](https://github.com/user-attachments/assets/b3eab82f-0a49-437b-a904-0ebcabc3434e)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="481" alt="image" src="https://github.com/user-attachments/assets/a0947859-58a5-4dce-9ab0-249513d49103">

从内存泄漏的堆栈来看，这个内存泄漏不是系统的问题？你确定找对人了？
