### ISSUE TITLE
输入法会把导航栏顶起来

### ISSUE THREAD

**Issue by OrangeHao** [getActivity/AndroidProject#2]

**Comment by getActivity** [comment]
你好，这个问题正在修复

**Comment by getActivity** [comment]
这个原因已经排查到，父布局为LinearLayout，因为 ViewPager 使用了权重的问题，软键盘在弹出的时候会把布局进行收缩，ViewPager 的高度缩小了，所以 BottomNavigationView 会显示在ViewPager 下面，解决方法是在 ViewPager 初始化高度后手动进行设置 ViewPager 高度并将权重设置为0

**Comment by sunjiaxin** [comment]
按照轮子哥的说法, 在HomeActivity 的initView 加上下面这句就行了. 

 ViewTreeObserver vto = mViewPager.getViewTreeObserver();
        vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                //防止键盘遮挡布局
                mViewPager.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                int pagerHeight = mViewPager.getHeight();
                LinearLayout.LayoutParams linearParams = (LinearLayout.LayoutParams) mViewPager.getLayoutParams(); // 取控件mGrid当前的布局参数
                linearParams.height = pagerHeight;// 当控件的高强制设成测量好的高
                linearParams.weight = 0;//
                mViewPager.setLayoutParams(linearParams); // 使设置好的布局参数应用到控件
            }
        });
