### ISSUE TITLE
提 issue 需知

### ISSUE THREAD

**Issue by getActivity** [getActivity/AndroidProject#20]
Github沟通效率实在是很低下，大家伙有问题或者Bug直接到Q群78797078私信给我反馈就OK，我会尽快答复你的问题

**Comment by zhulujiang** [comment]
项目不错，希望SettingBar里面像qq那样能把红点加进去就完美了

**Comment by getActivity** [comment]
你把 SettingBar 当做 FrameLayout 去用就可以了

**Comment by liverloop** [comment]
Wow, the project is great.
But there is a little flaw...
Will there be a module for network requests?

**Comment by sfy666666** [comment]
群怎么被禁言了，想问问题也问不了。。

**Comment by getActivity** [comment]
私信我即可

**Comment by LittleStart-007** [comment]
底部BottomNavigationView 长按会弹Toast

**Comment by getActivity** [comment]
这个是 Google 写死的，没办法关闭

**Comment by outsis** [comment]
嵌套太多层了，只想要一部分功能，却被迫引入全部的东西

**Comment by getActivity** [comment]
多谢建议哈，你可以把自己需要那一部分复制到项目中

**Comment by SmallWinter** [comment]
首先感谢大神辛劳！
提一个问题：InputDialog的方法（继承自BaseDialog）：
public void onDismiss(BaseDialog dialog){
getSystemService(InputMethodManager.class).hideSoftInputFromWindow(this.getCurrentFocus().getWindowToken(), 0);
}   隐藏输入法不会生效（mInput.getCurrentWondowToken()一样）。

个人拙见：隐藏输入法必须在父类方法onDismiss（）之前，不然dialog被销毁之后拿不到令牌，可能就会导致无法正确隐藏输入法。

**Comment by getActivity** [comment]
多谢小伙子提醒，我纠正了一下，在 BaseDialog dismiss 之前先隐藏输入法。

**Comment by yangwenwu** [comment]
如何屏蔽第一次启动进去   在其他应用上层显示

**Comment by yangwenwu** [comment]
我知道了，我要撤回上面提的这个问题

**Comment by zjc163** [comment]
Demo里面是不是缺了类com.hjq.demo.http.glide.GlideApp，报错了

**Comment by getActivity** [comment]
@zjc163 这个类是 Gradle 编译时生成的，你不用管，直接运行项目即可。

**Comment by LiuXingzhou** [comment]
考不考虑用上ViewBinding呀

**Comment by getActivity** [comment]
@LiuXingzhou 小伙子，暂时不考虑，原因在常见疑问上面有写了

**Comment by Pandaqing** [comment]
Demo中点开选择图片然后关闭,有内存泄漏？
    ├─ android.view.inputmethod.InputMethodManager class
    │    Leaking: NO (InputMethodManager↓ is not leaking and a class is never leaking)
    │    ↓ static InputMethodManager.sInstance
    ├─ android.view.inputmethod.InputMethodManager instance
    │    Leaking: NO (InputMethodManager is a singleton)
    │    Library leak match: instance field android.view.inputmethod.InputMethodManager#mLastSrvView
    │    ↓ InputMethodManager.mLastSrvView
    │                         ~~~~~~~~~~~~
    ├─ com.hjq.demo.widget.StatusLayout instance
    │    Leaking: YES (View.mContext references a destroyed activity)
    │    Retaining 341625 bytes in 4540 objects
    │    View not part of a window view hierarchy
    │    View.mAttachInfo is null (view detached)
    │    View.mID = R.id.hl_image_select_hint
    │    View.mWindowAttachCount = 1
    │    mContext instance of com.hjq.demo.ui.activity.ImageSelectActivity with mDestroyed = true
    │    ↓ StatusLayout.mContext
    ╰→ com.hjq.demo.ui.activity.ImageSelectActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.hjq.demo.ui.activity.ImageSelectActivity received
    ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     Retaining 44426 bytes in 826 objects
    ​     key = 13029545-1803-48a3-9d32-3c4d15464aed
    ​     watchDurationMillis = 5265
    ​     retainedDurationMillis = 263
    ​     mApplication instance of com.hjq.demo.app.AppApplication
    ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper, not wrapping known Android context

**Comment by getActivity** [comment]
小伙子，我按照你说的方式去操作了多次，并没有复现出来你说的这个内存泄漏的问题

**Comment by Pandaqing** [comment]
> 小伙子，我按照你说的方式去操作了很多，而且你说的这个内存没有复现出来的问题

那就奇怪了，我直接下载的Demo运行,在手机上操作进入相片选择(选择图片或者不选择图片--我的 Fragment-->点我进入选择图片界面),然后按返回或则标题栏上面的返回，就会提示这个.

**Comment by HoanChen** [comment]
> > 小伙子，我按照你说的方式去操作了很多，而且你说的这个内存没有复现出来的问题
> 
> 那就奇怪了，我直接下载的Demo运行,在手机上操作进入相片选择(选择图片或者不选择图片--我的 Fragment-->点我进入选择图片界面),然后按返回或则标题栏上面的返回，就会提示这个.

刚轮哥发的最新的apk  体验了一把  流畅丝滑   你的这个问题我好像也碰到了

**Comment by githubnimabi** [comment]
大佬，技术中台该更新一下库了哈，例如EasyHttp还是用的10.2

**Comment by getActivity** [comment]
@githubnimabi 小伙子，目前 AndroidProject 的策略是半年更新一次，一次更新半年的量，因为在更新的过程中代码是不稳定的，所以不会提交任何代码到 Github 上面。

**Comment by CileCile** [comment]
请问下能否适配下折叠屏手机，太难了o(╥﹏╥)o

**Comment by cyl1996219** [comment]
内存泄漏：先点登入见面-》再点分享界面-》再点登入界面。一共可以触发两次

**Comment by getActivity** [comment]
@cyl1996219 小伙子，提问题请通过创建新的 issue 来提，这里不再处理任何问题。
