### ISSUE TITLE
大哥在上,请问一下原生的Menu怎么添加。是需要用弹出菜单吗?

### ISSUE THREAD

**Issue by JonkMing** [getActivity/AndroidProject#21]
大哥在上,请问一下原生的Menu怎么添加。是需要用弹出菜单吗?
 @Override
    public boolean onCreateOptionsMenu(Menu menu) {

**Comment by 880634** [comment]
PopupWindow了解一下？

**Comment by JonkMing** [comment]
看来是别无选择了。 只能用这种方式了
