### ISSUE TITLE
你好，我这样用WaitDialog时，偶尔出现ProgressBarView消失，请问是什么原因？

### ISSUE THREAD

**Issue by zybooo1** [getActivity/AndroidProject#22]
` case R.id.btn_dialog_wait: // 等待对话框

                if(waitDialog==null){

                    waitDialog = new WaitDialog.Builder(this)

                            .create();

                }

                waitDialog.show();

                getHandler().postDelayed(new Runnable() {

                    @Override

                    public void run() {

                        waitDialog.dismiss();

                    }

                }, 3000);

                break;
`

**Comment by getActivity** [comment]
issue第一条已经说了，加群后私信我解决问题
