### ISSUE TITLE
Android9.0 侧滑返回用不了的更新提示 (顶楼主！！)

### ISSUE THREAD

**Issue by AlienChao** [getActivity/AndroidProject#26]
在UIActivity中加入

    /**
     * 滑动返回执行完毕，销毁当前 Activity
     */
    @Override
    public void onSwipeBackLayoutExecuted() {
        if(Build.VERSION.SDK_INT < Build.VERSION_CODES.P){
            mSwipeBackHelper.swipeBackward();
        }else{
            BGAKeyboardUtil.closeKeyboard(this);
            finish();
            overridePendingTransition(0,0);
        }
    }

**Comment by getActivity** [comment]
关于这个问题，我在新版本的处理方式是将界面侧滑功能移除

**Comment by getActivity** [comment]
多谢提醒
