### ISSUE TITLE
没有兼容Android Studio 3.5

### ISSUE THREAD

**Issue by walorwang** [getActivity/AndroidProject#29]
property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, D:\work_git\AndroidProject\app\build\intermediates\merged_manifests\baiduDebug))\AndroidManifest.xml (文件名、目录名或卷标语法不正确。)

**Comment by getActivity** [comment]
把 Gradle 版本回滚到 4.6 即可
