### ISSUE TITLE
EventBus,索引问题

### ISSUE THREAD

**Issue by sunchengjian** [getActivity/AndroidProject#33]
![图片](https://user-images.githubusercontent.com/28748459/69212397-21e9de00-0b9c-11ea-8886-f36d7336557b.png)
这个情况遇到过吗，我是在你的这个框架上做了一些其他的修改，但是eventbus这还没动呢，就出现这个问题了，查找了一上午没弄明白怎么回事，朋友有时间给看一下吗

**Comment by sunchengjian** [comment]
![图片](https://user-images.githubusercontent.com/28748459/69212500-79884980-0b9c-11ea-93bb-489dfaa18344.png)

**Comment by getActivity** [comment]
重新构建一下

**Comment by sunchengjian** [comment]
重新构建也不行

**Comment by getActivity** [comment]
在版本管理中看看修改了哪些东西

**Comment by sunchengjian** [comment]
已解决，是在引用dagger时，dagger的版本高了，更换一下可以了，
