### ISSUE TITLE
Android O及以下版本中ImageLoader加载图片不显示

### ISSUE THREAD

**Issue by sfy666666** [getActivity/AndroidProject#35]
Android O及以下版本中ImageLoader加载图片不显示，连xml文件中默认的占位图都不显示了
Android P或Q没问题
用studio的模拟器测试的
Nexus S Android5.1  WXGA Android6.0   Galaxy Nexus Android7.1.1   Pixel 3a Android8.1上均出现ImageLoader加载图片不显示问题
求教

**Comment by getActivity** [comment]
直接用 Glide 会出现吗

**Comment by sfy666666** [comment]
我先试试看

**Comment by sfy666666** [comment]
我加群啦，同意一下

**Comment by sfy666666** [comment]
试过了直接用
File file = new File(mAvatarUrl);
Glide.with(getActivity()).load(file).into(mAvatarView);
也加载不出来

**Comment by getActivity** [comment]
那就是 Glide 的问题，你到 https://github.com/bumptech/glide 反馈一下这个问题
