### ISSUE TITLE
好像没有完全支持androidx

### ISSUE THREAD

**Issue by candebbs** [getActivity/AndroidProject#37]
如题。

**Comment by getActivity** [comment]
是指哪块没有支持？

**Comment by candebbs** [comment]
我看了一些activity，有
`
import android.animation.AnimatorSet;
import android.animation.ObjectAnimator;
import android.content.Context;
import android.content.Intent;
import android.view.View;
import android.view.animation.AccelerateDecelerateInterpolator;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
`
类似这种，算不算？

**Comment by getActivity** [comment]
这些类在 AndroidX 上面没有
