### ISSUE TITLE
大神，少提交了一个GlideApp类

### ISSUE THREAD

**Issue by 1119405009** [getActivity/AndroidProject#38]
大神，少提交了一个GlideApp类

**Comment by getActivity** [comment]
GlideApp 是 Glide APT 插件自动生成的

**Comment by getActivity** [comment]
你应该是改了包名导致这个问题

**Comment by getActivity** [comment]
你参考一下这篇文章的第二种办法，不要用第一种：https://www.jianshu.com/p/17327e191d2e
