### ISSUE TITLE
关于启动页的问题

### ISSUE THREAD

**Issue by storm-zzz** [getActivity/AndroidProject#39]
刚启动的时候会白屏一段时间，然后打开 SplashActivity 的时候会有一个不明显的短暂的黑屏并且闪烁一下，手机是 Android 5.1 版本，虽然说无伤大雅，但还是希望大佬能修复一下这个小问题。

**Comment by getActivity** [comment]
我的手机没有出现这个问题，需要你到 QQ 群中联系我解决这个问题，并且提供这个 Bug 的一些更详细的信息，以及协助我排查和修复这个问题。
