### ISSUE TITLE
V11.1使用的网络请求框架6.9有问题

### ISSUE THREAD

**Issue by nszaaa3** [getActivity/AndroidProject#40]
当ReleaseServer的请求类型为JSON时，发送包含JSONArray类型的JSONObject作为请求，会反复走EasyUtils.mapToJsonObject()方法，导致内存泄漏。在QQ上给您留言没有回复。
![image](https://user-images.githubusercontent.com/15356343/88378204-21f94800-cdd3-11ea-9180-35f955ba012a.png)

**Comment by getActivity** [comment]
麻烦给一下 UnifiedLoginApi 类的源码

**Comment by nszaaa3** [comment]
这里是UnifiedLoginApi的源码以及ReleaseServer的配置，没有使用TestServer，只用了ReleaseServer
![FOR0{@@6_DWS5S7HH{MIK1T](https://user-images.githubusercontent.com/15356343/88380233-c204a080-cdd6-11ea-8809-de5253cae9a3.png)
![image](https://user-images.githubusercontent.com/15356343/88380317-efe9e500-cdd6-11ea-8fee-8376c24eefbf.png)

**Comment by nszaaa3** [comment]
这里是UnifiedLoginApi的代码以及ReleaseServer的配置，没有使用TestServer。
![image](https://user-images.githubusercontent.com/15356343/88380491-3fc8ac00-cdd7-11ea-92f2-1a304ce44ec6.png)

**Comment by getActivity** [comment]
使用一个 Bean 类代替 JsonObject 即可

**Comment by nszaaa3** [comment]
感谢您的解答，抱歉回复晚了，我试了您提示的创建了一个Parameter类代替JSONObject，仍在ReleaseServer里使用BodyType.JSON，依然会报同样的错误。于是我为此接着为parameter的子节点condition和page分别创建了类，又为condition的keyValueList创建了类，最终发送成功。结论还是：在发送请求时，参数内包含List类型时会报错。

**Comment by nszaaa3** [comment]
问题是出在了EasyUtils的beanToHashMap，如果传入的值包含一个List值，会走死循环mapToJsonObject，正在查看您的源码寻找解决办法。

**Comment by getActivity** [comment]
问题已经修复，你升级到 8.0 版本即可
