### ISSUE TITLE
日期时间控件能否结合一下出一个控件

### ISSUE THREAD

**Issue by chen3441251** [getActivity/AndroidProject#41]
年月日时分秒在一起的选择控件，最好是能做到可以按需显示/隐藏，比如只需要年月日，或者只需要时分秒，或者只需要年月日时分

**Comment by getActivity** [comment]
时间和日期选择的对话框已经有了，你如果有需要的话可以将这两者结合一下，AndroidProject 只集成常用的功能，而时间和日期同时出现的频率不高，所以不考虑对这两者进行结合。
