### ISSUE TITLE
弹窗问题

### ISSUE THREAD

**Issue by zhangzhen1129** [getActivity/AndroidProject#43]
弹窗为什么不用FragmentDialog 那  和dialog 那个更好一点？

**Comment by getActivity** [comment]
DialogFragment 最大的作用在于避免 Dialog 内存泄漏，BaseDialog 本身就已经自带生命周期管控了，之前旧版就用了 DialogFragment，但是发现太多细节上面的问题需要处理，处理了很多次但是仍然有问题，后面放弃直接监听 Activity 的生命周期了，替换之后到现在没有发现任何问题，说明这种方案是可行的，并且比 DialogFragment 更加优秀。
