### ISSUE TITLE
提一个建议，增加DialogFragment

### ISSUE THREAD

**Issue by candebbs** [getActivity/AndroidProject#46]
项目有基于Dialog的对话框，但可能有时不够用，比如有的对话框比较复杂，处理业务逻辑比较多，建议加一个可以自定义布局的DialogFragment。

**Comment by getActivity** [comment]
AndroidProject 已经把 DialogFragment 剔除了，因为用了另外一种方法处理 Dialog 生命周期的问题

**Comment by candebbs** [comment]
我是从业务逻辑方面来考虑的，觉得有时要加上dialogFragment的。
