### ISSUE TITLE
网络请求后没有判断activity是否销毁，如果销毁了再修改界面不会导致崩溃吗？

### ISSUE THREAD

**Issue by liu-xinhui** [getActivity/AndroidProject#47]
之前都是用rxjava或者livedata，destroy后就不更新界面了。这个框架都没有使用，直接网络请求后更新界面，如果此时activity已经destory了，不会导致崩溃吗？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/96852892-49bc8280-148c-11eb-923b-d6a9e4298df3.png)

**Comment by getActivity** [comment]
https://github.com/getActivity/EasyHttp

**Comment by liu-xinhui** [comment]
原来是网络请求框架自动处理呀，牛逼

**Comment by getActivity** [comment]
EasyHttp 用到了 Jetpack 中的 Lifecycle 特性来做请求的生命周期管控，在 AndroidX 包下的 AppCompatActivity 和 Fragment 都是 LifecycleOwner 的子类，所以无需自己封装。
