### ISSUE TITLE
AppCompatCheckBox的问题

### ISSUE THREAD

**Issue by candebbs** [getActivity/AndroidProject#49]
在findFragment下的AppCompatCheckBox，如果你快速点击AppCompatCheckBox时，或者按0.5秒这样点击，多点击几次后，发现AppCompatCheckBox状态切速不了的，点击多几下才切换状态的，通过log来查看.isChecked()方法看下选中的状态，有时输出状态是错的，有时没有输出，不知道是官方的bug还是项目的bug?

**Comment by getActivity** [comment]
```groovy
implementation 'androidx.appcompat:appcompat:1.3.0-alpha02'
implementation 'com.google.android.material:material:1.3.0-alpha02'
```

**Comment by getActivity** [comment]
你升级一下 AndroidX 的版本再试试

**Comment by candebbs** [comment]
升级了，还是一样的问题。

**Comment by getActivity** [comment]
那我也没有办法了，这个控件是原生的，我也没有修改过这个控件

**Comment by candebbs** [comment]
换成CheckBox就没有问题了。
