### ISSUE TITLE
希望加入通知的demo

### ISSUE THREAD

**Issue by candebbs** [getActivity/AndroidProject#51]
通知在app中很常见，也有一点机型适配的问题，为什么不考虑加入呢？

**Comment by getActivity** [comment]
谷歌 Support 包中不是有 NotificationCompat 这个类？

**Comment by getActivity** [comment]
还有 AndroidProject 的目标不是做一个 Demo，而是一个 App 架构，要分清楚概念。

**Comment by getActivity** [comment]
还有不要随便提 issue，从你给我提过的几个 issue 能看得出来你是新手上路，我个人建议你多学习多思考多实践，一有问题或者想法不应该第一时间反馈给别人，而是经过深层次的思考再进行反馈。再强调一下，我不是说不能提 issue，而是要三思而后行，否则会给我造成一些困扰。

**Comment by candebbs** [comment]
在我眼中（不是别人的眼中，也不知我眼中是否对不），我定义这个项目，是快速开发，拿到手，可以直接开发，不用考虑过多的东西，于是关注点在如何快速开发，不是在架构上（因为有大佬专门考虑了，我就能力有限不考虑，提供不了建议。）NotificationCompat ，我在github上没有找到好的框架，在网上找的demo和例子，测试过会机型适型的问题，所以建议加入。

**Comment by NicodeLee** [comment]
@candebbs 简单通知用官方Notification就足够了也不需要框架。
