### ISSUE TITLE
http请求，如果有多层泛型，会报错

### ISSUE THREAD

**Issue by liu-xinhui** [getActivity/AndroidProject#52]
![image](https://user-images.githubusercontent.com/7698511/99614820-3da8ee00-2a55-11eb-9ea5-1828f2de371b.png)
![image](https://user-images.githubusercontent.com/7698511/99614940-82cd2000-2a55-11eb-9acc-fe441285b55b.png)

**Comment by getActivity** [comment]
Gson 不支持这样解析吧？

**Comment by liu-xinhui** [comment]
是的，是我搞错了，gson本身就不支持这种
