### ISSUE TITLE
什么原因项目剔除掉了ButterKnife

### ISSUE THREAD

**Issue by forestAndroid** [getActivity/AndroidProject#53]

**Comment by getActivity** [comment]
* 随着 AndroidProject 的不断优化，ButterKnife 功能很强大，但是实际开发中，大多数人只用到了 BindView 和 OnClick 注解，在 OnClick 注解在我的项目中发现一个 Bug，就是有时候不会响应点击事件，这个问题并不是必现的。还有 BindView 注解只是在视觉上面将 View 和 ID 的关系更明显了，它其实不能为我们简化代码，因为使用 BindView 和 findViewById 的代码量是一样的。

* ButterKnife 最大的缺点是还会自动生成 ViewBinding 类，就算在类中只使用了一个 BindView，它也会生成这个类，其实这样是不太好的。考虑到这些情况，我在新版的 AndroidProject 上面移除了 ButterKnife 框架，其实 findViewById 一直挺好，只是我们没有认真思考过而已。

**Comment by forestAndroid** [comment]
谢谢，再提一个bug。应该是logcat库的问题，返回并退出应用后，出现一个AppCompatImageView的内存泄漏

**Comment by getActivity** [comment]
经过核查，确实存在这个问题，已经修复该问题，本次修复会在下个版本发布，多谢小伙子的提醒。

**Comment by is1988** [comment]
对于已经习惯了ButterKnife一键关联view，现在面临的是又要将xml里的id与activity的view进行手动绑定（其实没用黄油刀之前都是这么干的），如果页面复杂或者项目庞大，感觉就光做findviewbyID就要耗费一定的时间，有什么可以即不使用ButterKnife，又可以快速绑定视图ID的方法呢？

**Comment by getActivity** [comment]
https://github.com/getActivity/StudioPlugins

**Comment by getActivity** [comment]
@is1988 推荐一款 findViewById 插件给你

**Comment by is1988** [comment]
> @is1988 推荐一款 findViewById 插件给你

多谢，我现在就研究一下

**Comment by is1988** [comment]
@getActivity 大佬我加群一直进不去，趁你在想问一个问题，
你的fragment在集成myfragment时，里面包含了一个Activity，

```
HomeFragment extends MyFragment<HomeActivity>
MyFragment<A extends MyActivity> extends BaseFragment<A>
```

我想问一下尖括号里的Activity，或者说这个<A>在这里起什么作用，
我今天在你的框架里写demo时发现子fragment不写这个Activity也可以，
但是刚才在写findViewById时，这里报错了，需要强转，如果加上这个Activity就正常。
是不是这里起到上下文的作用？

实不相瞒我工作七年了，第一次见这么写，我只能说一句“技不如人甘拜下风”

`另外你给的插件真香`

**Comment by getActivity** [comment]
作用其实有两个：首先这里面的设计思想是让你能够快速定位 Fragment 所在的 Activity 类，另外一个是你在 Fragment 使用 getAttachActivity 获取的 Activity 不需要再次强转

**Comment by liverloop** [comment]
建议引进ViewBinding

**Comment by getActivity** [comment]
@liverloop 小伙子，我文档上面有写了不用 ViewBinding 的原因

#### 为什么没有用 ViewBinding

* 首先 ViewBinding 和 ButterKnife 有一个相同的毛病，就是自动生成一个类，然后在这个类里面进行 findViewById，但是有一个致命的缺点，每个 `Activity / Fragment / Dialog / Adapter` 都需要先初始化 ViewBinding 对象，因为每次生成的类名都是不固定的，所以无法在基类中封装处理，并且每次都要写 `binding.xxx` 才能操作控件。

```java
ActivityXxxxBinding.inflate binding = ActivityXxxxBinding.inflate(getLayoutInflater());
binding.tv_data_name.setText("字符串");
```

* 另外一个它会根据控件 id 作为属性的名称，这样会导致一个代码不规范的问题，如果在 xml 中控件的 id 命名符合规范了，会导致在 Java 代码中的命名不规范，如果在 Java 代码中的命名规范了，又会导致 xml 的 id 不符合规范了。而代码规范关系到后续的代码维护，是一个很重要的问题，不容忽视。

* 虽然 ViewBinding 是谷歌官方推荐的，但是我觉得并不完美，解决了 findViewById 的同时又带来了其他的问题，在关键问题上有问题和矛盾，直白点说这些问题都是硬伤。

* 正如我上面所说的，findViewById 一直挺好，只是我们没有认真思考过而已。

* 另外大家如果不想写 findViewById，我可以推荐一款自动生成 findViewById 的插件给大家：[FindViewByMe](https://plugins.jetbrains.com/plugin/8261-findviewbyme)
