### ISSUE TITLE
请教一下关于xml的命名规则

### ISSUE THREAD

**Issue by is1988** [getActivity/AndroidProject#55]
我在开发时Activity对应的XML命名一般都是与Activity类名打个颠倒。
比如类名叫SettingActivity，那么XML就叫activity_setting.xml，这样在layout文件夹里找XML文件时回很快。
但是看到作者demo里的命名是和类名顺序一致（setting_activity.xml），我想请教一下到底哪种命名规则是最规范或者最合理的？

这里也可以映射出类名的命名，比如一个增删改查的页面，之前我比较喜欢这样命名：
AddMsgActivity、DeleteMsgActivity、AmendMsgActivity、MsgListActivity、MsgDetailsActivity
后来就统一改成业务+功能的命名方式：
MsgAddActivity、MsgDeleteActivity、MsgAmendActivity、MsgListActivity、MsgDetailsActivity
这样看起来比较舒服，因为看你的代码写的很规范，所以我现在有点质疑我的写法了

**Comment by getActivity** [comment]
这块内容我之前有在 QQ 群讲过的，我现在把聊天记录发给你看一下吧

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/105666082-6cd75200-5f13-11eb-9f3f-25ec2c403fc7.png)
![](https://user-images.githubusercontent.com/28616817/105666115-82e51280-5f13-11eb-96f3-168745730fe6.png)
![](https://user-images.githubusercontent.com/28616817/105666143-955f4c00-5f13-11eb-91dd-62f307102aeb.png)

**Comment by getActivity** [comment]
小伙子，看完之后有啥疑问么

**Comment by is1988** [comment]
稍等，我这还看不到图片

**Comment by is1988** [comment]
看懂了，你是模块分类优先，我是以UI分类优先，我这种适合小项目，你这种可以通吃，感觉可以学一下你的命名了，谢谢大佬。

**Comment by liukai2530533** [comment]
如果使用的databinding的不适合activity_main前面加上模块名字哦
