### ISSUE TITLE
大哥，MessageDialog的Dialog这么好用，为什么不单独做一个包呢？

### ISSUE THREAD

**Issue by libern** [getActivity/AndroidProject#59]
大哥，MessageDialog的Dialog这么好用，为什么不单独做一个包呢？

**Comment by getActivity** [comment]
https://github.com/getActivity/AndroidProject/blob/master/HelpDoc.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8B%86%E6%88%90%E5%A4%9A%E4%B8%AA%E6%A1%86%E6%9E%B6%E6%9D%A5%E5%81%9A%E8%BF%99%E4%BB%B6%E4%BA%8B

**Comment by getActivity** [comment]
摘自：https://github.com/getActivity/AndroidProject/blob/master/HelpDoc.md

**Comment by libern** [comment]
谢谢大哥，但是别人如果设计风格不一样，其实好像可以提供接口给他们设置样式的

**Comment by getActivity** [comment]
涉及到 UI 的定制化，无论怎么做，永远都无法满足所有人的需求，甚至大部分人的需求都满足不了

**Comment by libern** [comment]
谢谢大哥
