### ISSUE TITLE
发现fragment里面的短信验证码输入框

### ISSUE THREAD

**Issue by sjq9026** [getActivity/AndroidProject#6]
点击获取验证码之后 如果光标在输入框里面，控件滑出屏幕范围的之后，随着验证码倒数会自动滚到输入框的位置

**Comment by getActivity** [comment]
你好，这个问题我刚刚仔细看了一下，确实存在，其引起的原因不是因为焦点冲突，而是TextView在不断更新自身的内容而导致父布局ScrollView回滚的，介于这个验证码控件在登录注册这种界面可以用得到，但是这些界面往往不需要滚动，所以不会导致这个问题发生，所以不予以修正此问题
