### ISSUE TITLE
轮子哥出品，必属废品

### ISSUE THREAD

**Issue by Liam6666** [getActivity/AndroidProject#60]
轮子哥出品，必属废品
蒙骗安卓开发新手

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737679-679bb000-7c01-11eb-8bbb-8cc3e09fa05b.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737758-90bc4080-7c01-11eb-9d37-b6c1de486db2.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737799-a467a700-7c01-11eb-828d-0108379bafca.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737832-b3e6f000-7c01-11eb-9bb8-9cad717c0c70.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737858-c19c7580-7c01-11eb-8c32-55f1c85627d7.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737878-ccefa100-7c01-11eb-8a7b-434b3d7b3d2f.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737953-eabd0600-7c01-11eb-8d3c-2e3f9a9d07e4.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737979-f6a8c800-7c01-11eb-93ed-1ee9682b59ca.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109737993-00323000-7c02-11eb-8c71-762396ae4961.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109738025-0e804c00-7c02-11eb-9c64-478406cf788e.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109738053-18a24a80-7c02-11eb-8d3a-4df2e03d243a.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109738098-2952c080-7c02-11eb-8d60-a925b1d86ed3.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109738117-340d5580-7c02-11eb-9dfa-92e3bf4f8a72.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109738135-3cfe2700-7c02-11eb-8560-bfbd9abad4e8.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109738151-44bdcb80-7c02-11eb-9f91-3bc0659a73ac.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/109738299-864e7680-7c02-11eb-8f38-7a123adcdd9b.png)

**Comment by getActivity** [comment]
就问你服不服

**Comment by Liam6666** [comment]
笑死人了

**Comment by Liam6666** [comment]
继续，我在看

**Comment by Yikinayi** [comment]
这个轮子哥就是个爱装逼的傻逼玩意  全是小号自己夸自己

**Comment by Liam6666** [comment]
是的，他发的都是包装自己

**Comment by Yikinayi** [comment]
整天在群里发自己的东西  然后我们公司大佬看了 大牙都笑掉了  全是鸡毛蒜皮的东西

**Comment by Liam6666** [comment]
也就能忽悠忽悠新手

**Comment by Liam6666** [comment]
全是废物轮子，一点用都没

**Comment by Yikinayi** [comment]
还不如培训公司 啥也不是

**Comment by Liam6666** [comment]
我听说1毛钱能买10个star

**Comment by Yikinayi** [comment]
> 就问你服不服

服你妈妈逼 傻逼玩意 
自己夸自己有意思?

**Comment by getActivity** [comment]
你觉得不好可以不用，没要求你一定要用

**Comment by Liam6666** [comment]
有一说一，轮子哥的作品真的一点用都没

**Comment by a750457103** [comment]
哈哈  终于有人说真话了

**Comment by a750457103** [comment]
这个什么轮子个  安卓毒瘤

**Comment by a750457103** [comment]
> 你觉得不好可以不用，没要求你一定要用

哈哈  终于有人说真话喷你了.  我也忍了好久了

**Comment by getActivity** [comment]
首先我做的开源不收你一分钱，其次你要是觉得不好可以不用，这样框架的好与坏真与假跟你一毛钱关系都没有，但是你这样说话是对开源作者极大的不尊重。
