### ISSUE TITLE
关于底部导航栏高度写死的问题

### ISSUE THREAD

**Issue by LLQQHH** [getActivity/AndroidProject#63]
之前我也有想说，导航栏高度写成wrap，然后间距通过padding处理，这样也能适配，但是当要求再导航栏里面加入未读消息小红点（数字）,这个时候我发现，因为一开始没有小红点，然后有消息后小红点的突然出现，因为高度是wrap，会导致导航栏整体高度突变，这种突变影响用户视觉体验，是不允许的，还有一些情况，就是选中的时候文字字号要变大，这个时候写成wrap，也会突变，所以后来我就只能把高度写死了！我看了其他大厂app即使加小红点，或者选中文字变大，整体高度没有突变！所以我不认为这是google不规范，反而是想我们规范
![image](https://user-images.githubusercontent.com/19651932/112410194-c6ae9980-8d55-11eb-8059-5e1d379f594b.png)

**Comment by getActivity** [comment]
抛开谷歌的实现过程不讲，最终的效果就是控件越界了，而我只是仅仅把手机的字体调大了，并没有设置条目的字体大小，那么谷歌这种方式还能称之为规范吗？

**Comment by getActivity** [comment]
小伙子，你还有其他想法或者建议不，没有的话我就只能关闭 issue 了。

**Comment by LLQQHH** [comment]
如果你非要高度跟着文字变化，你可以把高度也写成sp！不同的控件有不同的使用场景，而一种底部导航菜单的，使用了那么多app，看到的一般高度都是写死的！我还是认为这么设计合理！
