### ISSUE TITLE
当在build.gradle配置支持Kotlin的时候，编译后会出现找不到类com.hjq.demo.http.glide.GlideApp

### ISSUE THREAD

**Issue by foxcode7** [getActivity/AndroidProject#64]

**Comment by foxcode7** [comment]
以下为我配置Kotlin的方式：

外层build.gradle
![image](https://user-images.githubusercontent.com/7324556/115834424-ccc49280-a447-11eb-9560-d8e24141048a.png)
app build.gradle
![image](https://user-images.githubusercontent.com/7324556/115834522-e6fe7080-a447-11eb-9c69-73250f6206f2.png)
![image](https://user-images.githubusercontent.com/7324556/115834576-f382c900-a447-11eb-80c1-b7bf50587796.png)
![image](https://user-images.githubusercontent.com/7324556/115834610-fed5f480-a447-11eb-8cd8-fb49004bb5d3.png)

**Comment by foxcode7** [comment]
怀疑是apply plugin: 'kotlin-kapt'这句的问题，注释后GlideApp能自动生成。
但是又会报这个错：
![image](https://user-images.githubusercontent.com/7324556/115834817-347add80-a448-11eb-9964-4675dfad2dac.png)

**Comment by foxcode7** [comment]
加回apply plugin: 'kotlin-kapt'这句后，同时修改dependencies
![image](https://user-images.githubusercontent.com/7324556/115849902-ee2d7a80-a457-11eb-90e1-9c35f14451b2.png)
还是会报zip file is empty的错误

**Comment by foxcode7** [comment]
最后发现和aspectj的这款插件有关系：apply plugin: 'android-aspectjx'
注释后能够编译和安装，没出现zip file is empty的问题。
但是这个会影响项目中aop相关的权限申请、网络检查等功能。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/115894368-c526dd00-a48b-11eb-83fd-11fb34f0f908.png)
