### ISSUE TITLE
建议增加指纹识别或人脸识别对话框

### ISSUE THREAD

**Issue by fengzehao** [getActivity/AndroidProject#67]
有没有考虑下增加一个指纹识别或者人脸识别的对话框,我觉得应该用的人也不少   ^-^

**Comment by getActivity** [comment]
收到，首先非常感谢小伙子的建议，小伙子你虽然感觉用的人不少，但实际情况是，跟我提这个建议你还是第一个，所以我暂时不太可能会采纳，因为 AndroidProject 更想做的是一个架构设计，而不仅仅是一个 App 模板，当然写好一个模板同样也很重要，这是能极大提升大家的开发效率的，但是我只会加入项目开发中非常常见的功能又或者必须要用到的功能，而指纹识别和人脸识别现在在我看来还不满足我刚刚说的那两种类型。

**Comment by fengzehao** [comment]
好的，谢谢啦
