### ISSUE TITLE
关于在Activity中initView() initData() 被调用两次的疑问

### ISSUE THREAD

**Issue by HulkHou** [getActivity/AndroidProject#68]
轮子哥，您好！
请教您一个问题，具体问题如下：
在一个public final class QueryResultActivity extends AppActivity {}中，进入到这个Activity时，会调用一次initView() initData()，但是不知道什么原因，在onClick方法中，点击一个mCommitView时，initView() initData() 又会被调用一次，请问可能是什么原因导致的？
新人小白一个，麻烦了。

**Comment by getActivity** [comment]
小伙子，你确定 QueryResultActivity 这个类是 AndroidProject 里面的代码？

**Comment by HulkHou** [comment]
这个是我自己copy出来的一个activity。

**Comment by getActivity** [comment]
小伙子，因为 QueryResultActivity 这个类不是我写的，所以这个问题只能靠你自己去排查了，我没有这块的源码，想帮你也无能为力。

**Comment by HulkHou** [comment]
再次感谢！
