### ISSUE TITLE
使用控件SettingBar的bug

### ISSUE THREAD

**Issue by Davy103** [getActivity/AndroidProject#69]
大佬，在xml布局使用设置条自定义控件SettingBar，设置bar_lineMargin和bar_lineMargin属性无效，运行时提示空指针异常。

**Comment by getActivity** [comment]
[SettingBar.java.zip](https://github.com/getActivity/AndroidProject/files/6776159/SettingBar.java.zip)

**Comment by getActivity** [comment]
小伙子，这个问题之前有人反馈给我了，你可以下载这个压缩包，把类替换就行了。

**Comment by getActivity** [comment]
至于为什么没有及时更新到 Github 上面，是因为 AndroidProject 是半年左右更新一次，若非致命的 Bug，这期间不会提交任何代码。

**Comment by getActivity** [comment]
小伙子，你还有别的问题不，没有的话我就关闭 issue 了。

**Comment by Davy103** [comment]
好的，谢谢了
