### ISSUE TITLE
全屏对话框的问题

### ISSUE THREAD

**Issue by candebbs** [getActivity/AndroidProject#71]
假如定义一个充满全屏的对话框，弹出来时，手机顶部的状态栏是写黑色，不是沉浸式。

**Comment by getActivity** [comment]
https://github.com/gyf-dev/ImmersionBar

**Comment by getActivity** [comment]
这种使用问题就不要到这里提 issue 了，自己去找对应框架的文档不就好了吗

**Comment by candebbs** [comment]
我已经使用这个解决，我以为你定义对话框忘记考虑这一点。
