### ISSUE TITLE
功能问题

### ISSUE THREAD

**Issue by victorKaiDong** [getActivity/AndroidProject#73]
轮子哥这个框架里的PlayerView支持播放流媒体么，类似于rtmp://这种？

**Comment by getActivity** [comment]
小伙子，PlayerView 是基于原生 VideoView 进行封装的，而原生 VideoView 是不支持播放流媒体协议的视频，如果要做的话也不是没有办法实现，具体 AndroidProject 为什么不加入这个功能呢？因为他们携带了 so 库，一加入就会增大 apk 的体积，而一般应用对音视频播放的要求并没有那么高，只要能播放 mp4 的视频即可，如果你的项目对音视频的播放要求较高，请集成第三方框架或者修改 PlayerView 类来实现。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by victorKaiDong** [comment]
好的，非常感谢轮子哥的指教
