### ISSUE TITLE
图片选择器 加载速度太慢

### ISSUE THREAD

**Issue by buhanzhe** [getActivity/AndroidProject#74]
建议 参考https://github.com/LuckSiege/PictureSelector
优化加载速度
（
机型：红米K30至尊纪念版
系统版本：Android11
MIUI12.5
）
微信：buhanzhe

**Comment by buhanzhe** [comment]
Uploading 图片加载器卡.mp4…

**Comment by getActivity** [comment]
小伙子，有多慢？你录个视频过来我看一下。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
