### ISSUE TITLE
如何只设置view上边有阴影

### ISSUE THREAD

**Issue by tianshaokai** [getActivity/AndroidProject#75]
1，如题如何只设置view上边有阴影，其它三边没有阴影

**Comment by tianshaokai** [comment]
我设置了x y 偏移，不生效

**Comment by tianshaokai** [comment]
设置了阴影，左右 上下，就有 间距

**Comment by getActivity** [comment]
小伙子，不好意思，我昨天看错了，我还以为你说的是除了上边没有，其他边都有。

**Comment by getActivity** [comment]
@tianshaokai 你这个需求框架暂时实现不了，因为 Paint 在绘制阴影的时候没有提供这块的设置，建议你通过其他方式来实现。
