### ISSUE TITLE
clone构建时出错

### ISSUE THREAD

**Issue by hapzhu** [getActivity/AndroidProject#8]
我将项目克隆导入AS时，构建报如下错误，不知道是什么原因.
`Gradle sync failed: Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;`

我改动的地方就是gradle的版本变为最新版
  classpath 'com.android.tools.build:gradle:3.2.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

希望大侠您指导下哪里出错了，万分感谢

**Comment by getActivity** [comment]
改回去试一下
