### ISSUE TITLE
关于获取file路径问题

### ISSUE THREAD

**Issue by victorKaiDong** [getActivity/AndroidProject#80]
上传图片的时候，在Android10.0以下的设备，是正常上传的， 在Android10和11上，
获取到的file=content:/***设置给 setFile(file)，上传的时候就失败了。

**Comment by getActivity** [comment]
小伙子，排查到问题的原因了吗？

**Comment by getActivity** [comment]
小伙子，结果咋样了？还有你如果长时间不回复的话，我会认为你的问题已经解决了，我就会主动关闭这个 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
