### ISSUE TITLE
有没有快速使用手册

### ISSUE THREAD

**Issue by JaneYork** [getActivity/AndroidProject#81]
1. 有没有快速使用手册，快速上手的写法教程等

2. 有没有，介绍该项目的技术点，MVVM？集成框架？？包目录名？？网络请求？？

**Comment by getActivity** [comment]
小伙子，这个项目没有任何 API 文档，源码就是最好的老师，里面的注释已经写得很详细了，第三方框架的文档需要你自己去对应的框架主页看。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by JaneYork** [comment]
> 小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

加QQ群了，麻烦通过下

**Comment by JaneYork** [comment]
> 小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

1. 有咩有赋值的示例，http请求后，怎么赋值到表单，或者赋值到listview中

**Comment by getActivity** [comment]
小伙子，你这个问题不属于框架的问题，而是你自己的使用问题，我目前只处理和框架相关的问题。
