### ISSUE TITLE
提点引入第三方popup冲突的问题

### ISSUE THREAD

**Issue by candebbs** [getActivity/AndroidProject#82]
引入了：第三方的：XPopup，地址为：[https://github.com/li-xiaojun/XPopup](https://github.com/li-xiaojun/XPopup)，然后发现跟WrapRecyclerView产生bug，点击item，得到错误位置的position，比如点击第一个item，得到position是第5或6个，换成RecyclerView正常。
人菜看不出问题，找不到出在那一行代码上，于是提交issues，也不算issues吧。
写下来，让后面如果碰到这样的问题不坑。

**Comment by getActivity** [comment]
你是不是把 WrapRecyclerView 单独拿出去用了？如果是的话，那么得到的位置要减去头部的数量才可以，AndroidProject 之所以不用是因为它在 BaseAdapter 已经对位置做了处理了。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by candebbs** [comment]
没有加入头部和尾部，就是加了下拉刷新和加载更多，我直接把WrapRecyclerView当RecyclerView使用。我在最新版的androidProject引入了XPopup，但没有使用，也会出错同样的问题。

**Comment by getActivity** [comment]
没有加入头部或者尾部，你完全可以不用 WrapRecyclerView

**Comment by getActivity** [comment]
还有我只能保证 AndroidProject 的代码没有问题，如果你因为使用了其他框架导致的问题，请你自行对问题进行排查，我目前不处理框架之外的任何问题。

**Comment by candebbs** [comment]
好的，那我关了issues。
