### ISSUE TITLE
关于windowAnimationStyle的问题

### ISSUE THREAD

**Issue by victorKaiDong** [getActivity/AndroidProject#83]
我在AppTheme中设置
"android:windowAnimationStyle">@style/BottomAnimStyle
没有起作用，Activity单独设置Theme也无效，请问是什么原因？
![image](https://user-images.githubusercontent.com/33082314/142406491-e90da5ae-4669-4085-b6f1-64a69ffd5f5d.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/142554856-d4038c7d-902a-464a-99fd-40dcefbbcd4f.png)

**Comment by getActivity** [comment]
小伙子，你看看是不是这个原因导致的？

**Comment by victorKaiDong** [comment]
是的，这两行注释掉，就没有问题了，但是在继承AppActivity的activity里重写设置，为什么也不起作用呢

**Comment by getActivity** [comment]
小伙子，你这个问题不属于框架层面的问题，而是你个人使用的问题，我目前只处理和框架有关的问题，个人问题请自行排查和解决。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by victorKaiDong** [comment]
好的
