### ISSUE TITLE
关于沉浸式状态栏

### ISSUE THREAD

**Issue by victorKaiDong** [getActivity/AndroidProject#84]
我在一个继承AppActivity的类中，使用沉浸式状态栏，状态栏第一次已进入这个页面是黑色的
上下滑动后才变成了沉浸式

![1637659718](https://user-images.githubusercontent.com/33082314/143001272-72371eda-5e49-42a6-866e-cb44aa33ff66.jpg)

**Comment by getActivity** [comment]
小伙子，AndroidProject 上面提供的 Demo 是否有这个问题？

**Comment by victorKaiDong** [comment]
继承TitleBarFragment的类使用没有问题，但是集成AppActivity的类使用，都会出现这个问题，我在AndroidProject中创建了一个TestActivity，继承自AppActivity也有这种情况，代码完全1:1从HomeFragment搬过去的。我的手机是Mi 10， MIUI12.5.8稳定版，Android11 版本的。下边是我从首页跳转到新的Activity的问题复现视频

https://user-images.githubusercontent.com/33082314/143012755-0f5416ce-8831-4222-9206-bcf9e5985f34.mp4

**Comment by getActivity** [comment]
小伙子，麻烦你把刚刚视频里面的 AndroidProject 的代码打成压缩包发给我，记得发之前要把 build 目录删掉。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/143171152-969e94f3-0ce9-41ce-9c59-4bf534c0d726.png)
