### ISSUE TITLE
今天北京反诈中心给我打电话，让我卸载安卓技术中台这个demo，说有风险。。。。

### ISSUE THREAD

**Issue by liuzhenli** [getActivity/AndroidProject#86]

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/144831495-aa2740d8-1290-4966-a0ae-356a56a40588.jpg)

**Comment by yin-ol** [comment]
建议卸载反诈中心👀

**Comment by liuzhenli** [comment]
> 建议卸载反诈中心👀

我能说我都没有安装吗?吓的我赶紧安装了一个.哈哈哈哈

**Comment by ailuoyang** [comment]
我收到了广东反诈中心的电话
