### ISSUE TITLE
DebugLoggerTree 中createStackElementTag（...） //日志 TAG 长度限制判断是否写错？是不是8.0开始被移除限制

### ISSUE THREAD

**Issue by qianfeifeio** [getActivity/AndroidProject#87]
在子类DebugLoggerTree 中createStackElementTag（...） //日志 TAG 长度限制已经在 Android 7.0 被移除是 否写错了？？？Timber.kt  的createStackElementTag（。。。）方法中  第 223行写的注释是  // Tag length limit was removed in API 26.          Android 8.0 被移除？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/145159436-a968f61b-0ab2-4b26-b86b-c528c7c7b3ae.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/145159601-ccb1a1ff-4917-4fbb-82e5-e68a66ebbeef.png)

**Comment by getActivity** [comment]
收到，多谢小伙子的提醒，问题已经纠正了，下个版本会更新上去。
