### ISSUE TITLE
PickerLayoutManager 如果设置的数量不是3 上下滑动顶部和底部的无法选中

### ISSUE THREAD

**Issue by zhongmichael** [getActivity/AndroidProject#88]

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/146118089-07164bff-770e-45ad-8673-aa8f7cf86b71.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/146118105-0d0c1894-7732-4169-a863-8eed69d7e96d.png)

**Comment by getActivity** [comment]
小伙子，我试了一下，没有发现你说的这个问题

**Comment by zhongmichael** [comment]
你设置4试一下～

**Comment by zhongmichael** [comment]
> 小伙子，我试了一下，没有发现你说的这个问题

你设置4试一下

**Comment by getActivity** [comment]
不用试，这个选择器的条目只能是单数不能是双数，如果你需要支持双数，请自行修改源码来实现。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
