### ISSUE TITLE
如何向这个项目贡献代码？

### ISSUE THREAD

**Issue by longluo** [getActivity/AndroidProject#89]
想往里面增加一些功能，直接提merge吗？谢谢！

**Comment by getActivity** [comment]
小伙子，我建议你通过提建议的形式告知我有什么功能需要补充，因为 AndroidProject 设计的思想是，不是想做一个什么都做的杂货铺，而是做真正的一个技术架构，所以加功能这件事需要三思而后行，如果不是一个项目必备的功能，那么它很难会加入到里面去。

**Comment by longluo** [comment]
Thx :-)
