### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by ylmyg** [getActivity/AndroidProject#9]
当打开软件的时候需要赋予手机存储的权限，然后点击禁止，然后就会跳出权限管理的界面，此时点击返回键会一直提示"没有权限访问文件，请手动授予权限"，然后此时再权限管理里面给予软件全部权限，但是点击返回还是一直提示"没有权限访问文件，请手动授予权限"。华为手机 6.0

**Comment by getActivity** [comment]
极少数机型的问题，更新一下厂商的系统就可以了

**Comment by ylmyg** [comment]
魅族手机 7.0 进入软件没有权限请求弹出 是不是默认已经获取全部权限了？

**Comment by getActivity** [comment]
我刚刚又测试了一次，没有出现你描述的问题，可能是部分机型篡改了权限的API，请自行通知厂商，我这里不给予兼容，谢谢
