### ISSUE TITLE
FragmentPagerAdapter 刷新所有Fragment

### ISSUE THREAD

**Issue by blesslz** [getActivity/AndroidProject#90]
项目中的FragmentPagerAdapter如果刷新所有的子Fragment（更新数据）是无效的

**Comment by getActivity** [comment]
[FragmentPagerAdapter.java.zip](https://github.com/getActivity/AndroidProject/files/7894096/FragmentPagerAdapter.java.zip)

**Comment by getActivity** [comment]
小伙子，你用这个类再试试

**Comment by blesslz** [comment]
好 谢谢

**Comment by blesslz** [comment]
在FragmentPagerAdapter利用Invoke来更新每个Fragment中的数据应该也可以吧

**Comment by getActivity** [comment]
这个我没有试过，你可以自己试一下

**Comment by blesslz** [comment]
嗯嗯 刚试了 控制局部刷新。可以。
