### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by SillyBoy93** [getActivity/AndroidProject#96]
在demo中，点击【我的】-> 【点我进入设置界面】->【关于我们】，然后回到【我的】，等几秒钟LeakCanary抱内存溢出。

**Comment by getActivity** [comment]
请贴出内存泄漏的完整堆栈截图

**Comment by SillyBoy93** [comment]
> 请贴出内存泄漏的完整堆栈截图

┬───
│ GC Root: System class
│
├─ [android.app.ActivityThread](http://android.app.activitythread/) class
│    Leaking: NO (a class is never leaking)
│    ↓ static [ActivityThread.sCurrentActivityThread](http://activitythread.scurrentactivitythread/)
│                            ~~~~~~~~~~~~~~~~~~~~~~
├─ [android.app.ActivityThread](http://android.app.activitythread/) instance
│    Leaking: UNKNOWN
│    Retaining [1.3](tel:1.3) MB in [4062](tel:4062) objects
│    mInitialApplication instance of [com.hjq.demo.app.AppApplication](http://com.hjq.demo.app.appapplication/)
│    mSystemContext instance of [android.app.ContextImpl](http://android.app.contextimpl/)
│    mSystemUiContext instance of [android.app.ContextImpl](http://android.app.contextimpl/)
│    ↓ [ActivityThread.mNewActivities](http://activitythread.mnewactivities/)
│                     ~~~~~~~~~~~~~~
├─ [android.app.ActivityThread](http://android.app.activitythread/)$ActivityClientRecord instance
│    Leaking: UNKNOWN
│    Retaining [1.3](tel:1.3) MB in [3693](tel:3693) objects
│    activity instance of [com.hjq.demo.ui.activity.HomeActivity](http://com.hjq.demo.ui.activity.homeactivity/) with mDestroyed
│    = false
│    ↓ ActivityThread$[ActivityClientRecord.nextIdle](http://activityclientrecord.nextidle/)
│                                          ~~~~~~~~
├─ [android.app.ActivityThread](http://android.app.activitythread/)$ActivityClientRecord instance
│    Leaking: UNKNOWN
│    Retaining [1.3](tel:1.3) MB in [3641](tel:3641) objects
│    activity instance of [com.hjq.demo.ui.activity.SettingActivity](http://com.hjq.demo.ui.activity.settingactivity/) with
│    mDestroyed = true
│    ↓ ActivityThread$[ActivityClientRecord.activity](http://activityclientrecord.activity/)
│                                          ~~~~~~~~
╰→ [com.hjq.demo.ui.activity.SettingActivity](http://com.hjq.demo.ui.activity.settingactivity/) instance
​     Leaking: YES (ObjectWatcher was watching this because [com.hjq.demo.ui](http://com.hjq.demo.ui/).
​     [activity.SettingActivity](http://activity.settingactivity/) received Activity#onDestroy() callback and
​     Activity#mDestroyed is true)
​     Retaining [52.0](tel:52.0) kB in [909](tel:909) objects
​     key = 5c75ad1c-d[099-43](tel:099-43)fb-bd98-b46d[8603054](tel:8603054)c
​     watchDurationMillis = [5154](tel:5154)
​     retainedDurationMillis = [141](tel:141)
​     mApplication instance of [com.hjq.demo.app.AppApplication](http://com.hjq.demo.app.appapplication/)
​     mBase instance of [androidx.appcompat.view.ContextThemeWrapper](http://androidx.appcompat.view.contextthemewrapper/)

METADATA

[Build.VERSION](http://build.version/).SDK_INT: 29
[Build.MANUFACTURER](http://build.manufacturer/): OPPO
LeakCanary version: [2.7](tel:2.7)
App process name: [com.hjq.demo](http://com.hjq.demo/)
Stats: LruCache[maxSize=[3000](tel:3000),hits=[5979](tel:5979),misses=[70075](tel:70075),hitRate=7%]
RandomAccess[bytes=[3809188](tel:3809188),reads=[70075](tel:70075),travel=[27817115831](tel:27817115831),range=[19088832](tel:19088832),size=23
[940948](tel:940948)]
Heap dump reason: 8 retained objects, app is visible
Analysis duration: [7024](tel:7024) ms

**Comment by getActivity** [comment]
小伙子，从内存泄漏的堆栈来看，和我的代码没有太大的关系，看着是系统的内存泄漏，你可以不需要理会这个问题。

**Comment by SillyBoy93** [comment]
好的，谢谢
