### ISSUE TITLE
WrapRecyclerView问题

### ISSUE THREAD

**Issue by blesslz** [getActivity/AndroidProject#97]
不设置header和footer的情况下条目点击无效，如果设置了有时候点击条目也不灵敏，另外点击的条目索引是乱序的

**Comment by getActivity** [comment]
[WrapRecyclerView.java.zip](https://github.com/getActivity/AndroidProject/files/9033008/WrapRecyclerView.java.zip)

**Comment by getActivity** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/28616817/177000577-f1d5ba7a-93be-4296-8e2e-e9f95f42f357.png">

**Comment by getActivity** [comment]
小伙子， 你换成这个类再试试看有没有这个问题。

**Comment by getActivity** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/28616817/177000928-9215c9bc-600f-417d-8db3-23c0cc25ed7c.png">

**Comment by getActivity** [comment]
小伙子， 你修改这两处地方，然后再试试看有没有问题。

**Comment by blesslz** [comment]
也不行呢

**Comment by blesslz** [comment]
滑动几页就点击没响应了，只有第一页点击有响应

**Comment by getActivity** [comment]
[AndroidProject_v1.0_preview.apk.zip](https://github.com/getActivity/AndroidProject/files/9040614/AndroidProject_v1.0_preview.apk.zip)

**Comment by getActivity** [comment]
@blesslz 小伙子，你用这个 apk 试试看是否有这个问题？

1. 如果有的话：请直接录屏上传到这里来？

2. 如果没有的话：请先排查你的代码写法是否有问题？

    * 如果没有找到是哪里的代码有问题，那么请提供能够复现这个问题的 Demo 工程源码

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
