### ISSUE TITLE
 ActivityManager.getInstance().getTopActivity()

### ISSUE THREAD

**Issue by blesslz** [getActivity/AndroidProject#98]
魅族手机发现调起分享再回到app之后ActivityManager.getInstance().getTopActivity()获取到的activity进行（activity == null || activity.isFinishing() || activity.isDestroyed()）判断是不存在的

**Comment by getActivity** [comment]
@blesslz 小伙子，你这边总共说了三个判断，是哪个判断为 true ？哪个判断为 false ？还有你在什么时机做的判断？

**Comment by blesslz** [comment]
在一下两种情况出现的：
1/从当前activity选择图片回调之后调用基类的showDialog(), isDestroyed是true   （红米手机出现）
2/从当前activity调起微信分享完成返回app之后，在回调中获取topActivity的destroyed是true     （魅族手机出现）

**Comment by blesslz** [comment]
另外 老哥 用编译版本为31的时候 报错：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:base:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by getActivity** [comment]
@blesslz 编译版本为 31 的问题报错，这个是你自己的问题，需要你自己看一下，我目前只处理框架的 Bug 和建议。

**Comment by getActivity** [comment]
> 1/从当前活动启动微信米手机完成返回的情况： 1/从当前活动启动图片调出后显示在调用类型的对话框中（调用基类的），isDes是真的（）中获取topActivity的破坏是真的（魅族手机出现）

@blesslz 如果不用 AndroidProject 的话，自己写一个 Demo 的话是否有也有这个问题？

**Comment by 979881765** [comment]
编译版本为 31   我就是用androidProject 这个Demo工程试的

**Comment by getActivity** [comment]
AndroidProject 当前的编译版本就是 30，如果你没改有问题可以来找我，毕竟这是我的事情没做好，但是你自己改成了 31 出现了问题，那就是你自己的问题了，需要你自己去兼容了，你如果不想花时间和精力做兼容，那么就把编译版本回退到 30，就是这么简单。

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
