### ISSUE TITLE
轮子哥大佬,一点疑问?

### ISSUE THREAD

**Issue by lydlovezjr** [getActivity/AndroidProject#99]
轮子哥,你好,我记得咱们这个项目最早的版本应该是对Glide进行过二次封装.
最新的版本好像没有封装了吧.
这个原因是?
我在常见问题中找了一圈没找到.
希望大佬万忙之中,看到的话,抽出宝贵时间回答一下.
万分感谢

**Comment by getActivity** [comment]
文档上面不是有写？

**Comment by lydlovezjr** [comment]
文档是那个,我没找到

**Comment by getActivity** [comment]
你确定自己完完整整一字不落把文档过了一遍了？
